/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 25 14:53:02 GMT 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ValueNode;
import java.io.File;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.avro.NameValidator;
import org.apache.avro.ParseContext;
import org.apache.avro.Schema;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Schema$Parser_ESTest extends Schema$Parser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      String[] stringArray0 = new String[3];
      // Undeclared exception!
      try { 
        schema_Parser0.parse("com.fasterxml.jackson.core.JsonPointer$PointerParent", stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'com': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
         //  at [Source: (String)\"com.fasterxml.jackson.core.JsonPointer$PointerParentnullnullnull\"; line: 1, column: 4]
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      ArrayList<Schema> arrayList0 = new ArrayList<Schema>(0);
      Schema schema0 = Schema.createUnion((List<Schema>) arrayList0);
      List<Schema> list0 = List.of(schema0);
      // Undeclared exception!
      try { 
        schema_Parser0.addTypes((Iterable<Schema>) list0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // You can only put a named schema into the context
         //
         verifyException("org.apache.avro.ParseContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(true);
      ValueNode valueNode0 = jsonNodeFactory0.pojoNode(schema_Parser0);
      // Undeclared exception!
      try { 
        Schema.parse((JsonNode) valueNode0, parseContext0, "");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Schema not yet supported: {\"validateDefaults\":true,\"types\":{}}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      HashMap<String, Schema> hashMap0 = new HashMap<String, Schema>();
      Schema.Parser schema_Parser1 = schema_Parser0.addTypes((Map<String, Schema>) hashMap0);
      assertTrue(schema_Parser1.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      // Undeclared exception!
      try { 
        schema_Parser0.parse((File) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      assertTrue(schema_Parser0.getValidateDefaults());
      
      schema_Parser0.setValidateDefaults(false);
      assertFalse(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      // Undeclared exception!
      try { 
        schema_Parser0.parse((InputStream) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Cannot parse <null> schema
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }
}
