/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 25 14:51:53 GMT 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.node.TextNode;
import java.time.DayOfWeek;
import java.util.HashMap;
import java.util.Set;
import org.apache.avro.NameValidator;
import org.apache.avro.ParseContext;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Schema$Field_ESTest extends Schema$Field_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("logicalType", schema0, "a|(r3bxG)s");
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field1 = new Schema.Field("logicalType", schema0, "logicalType", "a|(r3bxG)s", schema_Field_Order0);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertFalse(boolean0);
      assertEquals("a|(r3bxG)s", schema_Field0.doc());
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("logiclTye", schema0, "a|(r3bxG)s");
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertTrue(schema_Field1.equals((Object)schema_Field0));
      
      schema_Field0.addProp("logiclTye", "logiclTye");
      boolean boolean0 = schema_Field1.equals(schema_Field0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("logicalType", schema0, "a|(r3bxG)s");
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field1 = new Schema.Field("logicalType", schema0, "a|(r3bxG)s", (JsonNode) null, false, schema_Field_Order0);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertEquals("a|(r3bxG)s", schema_Field1.doc());
      assertFalse(boolean0);
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("logiclTye", schema0, "a|(r3bxG)s");
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      boolean boolean0 = schema_Field1.equals(schema_Field0);
      assertEquals((-1), schema_Field1.pos());
      assertTrue(boolean0);
      assertEquals("a|(r3bxG)s", schema_Field1.doc());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("lgcalType", schema0, "a|(r3bxG)s");
      Schema schema1 = Schema.createArray(schema0);
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema1);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertFalse(boolean0);
      assertEquals("a|(r3bxG)s", schema_Field1.doc());
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("logiclTye", schema0);
      Schema.Field schema_Field1 = new Schema.Field("logicalType", schema0, "Order cannot be null");
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertFalse(boolean0);
      assertEquals((-1), schema_Field1.pos());
      assertEquals("Order cannot be null", schema_Field1.doc());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("DESCENDI", schema0, "DESCENDI");
      boolean boolean0 = schema_Field0.equals(schema0);
      assertFalse(boolean0);
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("logiclTye", schema0, "a|(r3bxG)s", (JsonNode) null, false, schema_Field_Order0);
      boolean boolean0 = schema_Field0.equals(schema_Field0);
      assertEquals("a|(r3bxG)s", schema_Field0.doc());
      assertTrue(boolean0);
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("logiclTye", schema0);
      Schema.Field schema_Field1 = new Schema.Field("logiclTye", schema0, "logiclTye", "logiclTye");
      boolean boolean0 = schema_Field1.equals(schema_Field0);
      assertEquals((-1), schema_Field1.pos());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("DESCENDI", schema0, "DESCENDI");
      schema_Field0.aliases();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("logicalType", schema0, "a|(r3bxG)s");
      schema_Field0.addAlias("logicalType");
      Set<String> set0 = schema_Field0.aliases();
      assertEquals((-1), schema_Field0.pos());
      assertTrue(set0.contains("logicalType"));
      assertEquals("a|(r3bxG)s", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("logicalType", schema0, "a|(r3bxG)s");
      schema_Field0.addAlias("logicalType");
      schema_Field0.addAlias("a|(r3bxG)s");
      assertEquals((-1), schema_Field0.pos());
      assertEquals("a|(r3bxG)s", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      DayOfWeek dayOfWeek0 = DayOfWeek.WEDNESDAY;
      DayOfWeek dayOfWeek1 = dayOfWeek0.minus((-1510L));
      Schema.Field schema_Field0 = new Schema.Field("zWZ", schema0, "", dayOfWeek1);
      boolean boolean0 = schema_Field0.hasDefaultValue();
      assertEquals("", schema_Field0.doc());
      assertTrue(boolean0);
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("logiclTye", schema0, "a|(r3bxG)s");
      boolean boolean0 = schema_Field0.hasDefaultValue();
      assertFalse(boolean0);
      assertEquals((-1), schema_Field0.pos());
      assertEquals("a|(r3bxG)s", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("%uIM5Kz6qYh", schema0, "%uIM5Kz6qYh", object0, schema_Field_Order0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Illegal initial character: %uIM5Kz6qYh
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("XP)kIQStRXef*([+", schema0, "XP)kIQStRXef*([+", object0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Illegal character in: XP)kIQStRXef*([+
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("logiclTye", schema0, "logiclTye", "logiclTye");
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field1 = new Schema.Field("logiclTye", schema0, "org.apache.avro.Schema$Field$Order", "a|(r3bxG)s", schema_Field_Order0);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertEquals("org.apache.avro.Schema$Field$Order", schema_Field1.doc());
      assertFalse(boolean0);
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("logicalType", schema0, "a|(r3bxG)s");
      schema_Field0.addAlias("logicalType");
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertEquals("a|(r3bxG)s", schema_Field1.doc());
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("logicalType", schema0, "logicalType");
      int int0 = schema_Field0.pos();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("DESCENDI", schema0, "DESCENDI");
      schema_Field0.defaultVal();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("DESCENDI", schema0, "DESCENDI");
      schema_Field0.hashCode();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("ESENDING", schema0, "ESENDING");
      schema_Field0.doc();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("logicalType", schema0, "logicalType");
      String string0 = schema_Field0.toString();
      assertEquals("logicalType type:STRING pos:-1", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("ESENDING", schema0, "ESENDING");
      schema_Field0.name();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.NULL;
      Schema schema0 = Schema.create(schema_Type0);
      Schema.Field schema_Field0 = new Schema.Field("logicalType", schema0, "[''Wmt84Q-w,o@<");
      schema_Field0.defaultValue();
      assertEquals("[''Wmt84Q-w,o@<", schema_Field0.doc());
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("ESENDING", schema0, "ESENDING");
      schema_Field0.schema();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(false);
      HashMap<String, JsonNode> hashMap0 = new HashMap<String, JsonNode>();
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0, hashMap0);
      TextNode textNode0 = objectNode0.textNode("aIv83");
      NameValidator nameValidator0 = mock(NameValidator.class, new ViolatedAssumptionAnswer());
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema0 = Schema.parse((JsonNode) textNode0, parseContext0, "aIv83");
      ArrayNode arrayNode0 = new ArrayNode(jsonNodeFactory0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
      Schema.Field schema_Field0 = new Schema.Field("aIv83", schema0, "aIv83", arrayNode0, false, schema_Field_Order0);
      schema_Field0.order();
      assertEquals((-1), schema_Field0.pos());
  }
}
