/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 11 14:33:53 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.Instant;
import java.util.LinkedList;
import java.util.List;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$TimestampNanosConversion_ESTest extends TimeConversions$TimestampNanosConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Instant instant0 = MockInstant.ofEpochSecond((-1000000000L));
      LinkedList<Schema> linkedList0 = new LinkedList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) linkedList0);
      LogicalType logicalType0 = new LogicalType("uo|r7-}?");
      Long long0 = timeConversions_TimestampNanosConversion0.toLong(instant0, schema0, logicalType0);
      assertEquals((-1000000000000000000L), (long)long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Long long0 = new Long(1709L);
      Schema schema0 = Schema.createArray((Schema) null);
      LogicalType logicalType0 = new LogicalType("eERxh<(/?IX-");
      Instant instant0 = timeConversions_TimestampNanosConversion0.fromLong(long0, schema0, logicalType0);
      Instant instant1 = MockInstant.minusSeconds(instant0, 1000000000L);
      Long long1 = timeConversions_TimestampNanosConversion0.toLong(instant1, schema0, logicalType0);
      assertEquals((-999999999000998291L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Class<Instant> class0 = timeConversions_TimestampNanosConversion0.getConvertedType();
      assertFalse(class0.isPrimitive());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      String string0 = timeConversions_TimestampNanosConversion0.getLogicalTypeName();
      assertEquals("timestamp-nanos", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      String string0 = timeConversions_TimestampNanosConversion0.adjustAndSetValue("timestamp-nanos", "timestamp-nanos");
      assertEquals("timestamp-nanos = timestamp-nanos.truncatedTo(java.time.temporal.ChronoUnit.NANOS);", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Long long0 = new Long(1709L);
      Schema schema0 = Schema.createArray((Schema) null);
      LogicalType logicalType0 = new LogicalType("eERxh<(/?IX-");
      Instant instant0 = timeConversions_TimestampNanosConversion0.fromLong(long0, schema0, logicalType0);
      Long long1 = timeConversions_TimestampNanosConversion0.toLong(instant0, schema0, logicalType0);
      assertEquals(1709L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Schema schema0 = timeConversions_TimestampNanosConversion0.getRecommendedSchema();
      assertEquals(Schema.Type.LONG, schema0.getType());
  }
}
