/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 11 14:33:28 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalTime;
import java.util.List;
import java.util.Vector;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$TimeMillisConversion_ESTest extends TimeConversions$TimeMillisConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.TimeMillisConversion timeConversions_TimeMillisConversion0 = new TimeConversions.TimeMillisConversion();
      String string0 = timeConversions_TimeMillisConversion0.adjustAndSetValue("time-millis", "time-millis");
      assertEquals("time-millis = time-millis.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.TimeMillisConversion timeConversions_TimeMillisConversion0 = new TimeConversions.TimeMillisConversion();
      Vector<Schema> vector0 = new Vector<Schema>(25, 25);
      Schema schema0 = Schema.createUnion((List<Schema>) vector0);
      // Undeclared exception!
      try { 
        timeConversions_TimeMillisConversion0.toInt((LocalTime) null, schema0, (LogicalType) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.data.TimeConversions$TimeMillisConversion", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.TimeMillisConversion timeConversions_TimeMillisConversion0 = new TimeConversions.TimeMillisConversion();
      String string0 = timeConversions_TimeMillisConversion0.getLogicalTypeName();
      assertEquals("time-millis", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.TimeMillisConversion timeConversions_TimeMillisConversion0 = new TimeConversions.TimeMillisConversion();
      Class<LocalTime> class0 = timeConversions_TimeMillisConversion0.getConvertedType();
      assertFalse(class0.isInterface());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.TimeMillisConversion timeConversions_TimeMillisConversion0 = new TimeConversions.TimeMillisConversion();
      Schema schema0 = timeConversions_TimeMillisConversion0.getRecommendedSchema();
      LogicalType logicalType0 = new LogicalType("o<[E3b.>~M");
      // Undeclared exception!
      try { 
        timeConversions_TimeMillisConversion0.fromInt((Integer) null, schema0, logicalType0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.data.TimeConversions$TimeMillisConversion", e);
      }
  }
}
