/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 11 16:52:33 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.Instant;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$TimestampMicrosConversion_ESTest extends TimeConversions$TimestampMicrosConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Instant instant0 = MockInstant.ofEpochMilli((-1L));
      Schema.Type schema_Type0 = Schema.Type.NULL;
      Schema schema0 = Schema.create(schema_Type0);
      LogicalType logicalType0 = new LogicalType("WLxd!_,G`I");
      Long long0 = timeConversions_TimestampMicrosConversion0.toLong(instant0, schema0, logicalType0);
      assertEquals((-1000L), (long)long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      MockDate mockDate0 = new MockDate((-701), (-701), (-701));
      Instant instant0 = mockDate0.toInstant();
      LogicalType logicalType0 = new LogicalType("");
      Long long0 = timeConversions_TimestampMicrosConversion0.toLong(instant0, (Schema) null, logicalType0);
      assertEquals((-26233977600000000L), (long)long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Long long0 = Long.valueOf(0L);
      Schema schema0 = timeConversions_TimestampMicrosConversion0.getRecommendedSchema();
      LogicalType logicalType0 = new LogicalType("timestamp-micros");
      Instant instant0 = timeConversions_TimestampMicrosConversion0.fromLong(long0, schema0, logicalType0);
      assertNotNull(instant0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      String string0 = timeConversions_TimestampMicrosConversion0.adjustAndSetValue("", "");
      assertEquals(" = .truncatedTo(java.time.temporal.ChronoUnit.MICROS);", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Class<Instant> class0 = timeConversions_TimestampMicrosConversion0.getConvertedType();
      assertFalse(class0.isPrimitive());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Schema schema0 = timeConversions_TimestampMicrosConversion0.getRecommendedSchema();
      Instant instant0 = MockInstant.ofEpochMilli(2818L);
      LogicalType logicalType0 = new LogicalType("[Gv!.!Dq2v-?@<103AY");
      Long long0 = timeConversions_TimestampMicrosConversion0.toLong(instant0, schema0, logicalType0);
      assertEquals(2818000L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      String string0 = timeConversions_TimestampMicrosConversion0.getLogicalTypeName();
      assertEquals("timestamp-micros", string0);
  }
}
