/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 11 16:52:08 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$DateConversion_ESTest extends TimeConversions$DateConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.DateConversion timeConversions_DateConversion0 = new TimeConversions.DateConversion();
      Class<LocalDate> class0 = timeConversions_DateConversion0.getConvertedType();
      assertEquals("class java.time.LocalDate", class0.toString());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.DateConversion timeConversions_DateConversion0 = new TimeConversions.DateConversion();
      LocalDate localDate0 = MockLocalDate.now();
      Schema schema0 = Schema.createFixed((String) null, (String) null, (String) null, 53);
      Integer integer0 = timeConversions_DateConversion0.toInt(localDate0, schema0, (LogicalType) null);
      assertEquals(16115, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.DateConversion timeConversions_DateConversion0 = new TimeConversions.DateConversion();
      Schema schema0 = timeConversions_DateConversion0.getRecommendedSchema();
      LogicalType logicalType0 = new LogicalType("KV");
      // Undeclared exception!
      try { 
        timeConversions_DateConversion0.fromInt((Integer) null, schema0, logicalType0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.data.TimeConversions$DateConversion", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.DateConversion timeConversions_DateConversion0 = new TimeConversions.DateConversion();
      String string0 = timeConversions_DateConversion0.getLogicalTypeName();
      assertEquals("date", string0);
  }
}
