/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 11 16:52:58 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$LocalTimestampNanosConversion_ESTest extends TimeConversions$LocalTimestampNanosConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.LocalTimestampNanosConversion timeConversions_LocalTimestampNanosConversion0 = new TimeConversions.LocalTimestampNanosConversion();
      Class<LocalDateTime> class0 = timeConversions_LocalTimestampNanosConversion0.getConvertedType();
      assertFalse(class0.isPrimitive());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.LocalTimestampNanosConversion timeConversions_LocalTimestampNanosConversion0 = new TimeConversions.LocalTimestampNanosConversion();
      String string0 = timeConversions_LocalTimestampNanosConversion0.getLogicalTypeName();
      assertEquals("local-timestamp-nanos", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.LocalTimestampNanosConversion timeConversions_LocalTimestampNanosConversion0 = new TimeConversions.LocalTimestampNanosConversion();
      ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutesSeconds(0, 0, 0);
      LocalDateTime localDateTime0 = MockLocalDateTime.now((ZoneId) zoneOffset0);
      LogicalType logicalType0 = new LogicalType(" / 0x");
      Long long0 = timeConversions_LocalTimestampNanosConversion0.toLong(localDateTime0, (Schema) null, logicalType0);
      assertEquals(1392409281320000000L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.LocalTimestampNanosConversion timeConversions_LocalTimestampNanosConversion0 = new TimeConversions.LocalTimestampNanosConversion();
      Schema schema0 = timeConversions_LocalTimestampNanosConversion0.getRecommendedSchema();
      LogicalType logicalType0 = new LogicalType("local-timestamp-nanos");
      // Undeclared exception!
      try { 
        timeConversions_LocalTimestampNanosConversion0.fromLong((Long) null, schema0, logicalType0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.data.TimeConversions$TimestampNanosConversion", e);
      }
  }
}
