/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 11 15:42:43 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.LocalTime;
import java.util.List;
import java.util.Vector;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$TimeMicrosConversion_ESTest extends TimeConversions$TimeMicrosConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.TimeMicrosConversion timeConversions_TimeMicrosConversion0 = new TimeConversions.TimeMicrosConversion();
      Long long0 = new Long(1675L);
      Vector<Schema> vector0 = new Vector<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) vector0);
      LogicalType logicalType0 = new LogicalType("");
      LocalTime localTime0 = timeConversions_TimeMicrosConversion0.fromLong(long0, schema0, logicalType0);
      Long long1 = timeConversions_TimeMicrosConversion0.toLong(localTime0, schema0, logicalType0);
      assertTrue(long1.equals((Object)long0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.TimeMicrosConversion timeConversions_TimeMicrosConversion0 = new TimeConversions.TimeMicrosConversion();
      String string0 = timeConversions_TimeMicrosConversion0.getLogicalTypeName();
      assertEquals("time-micros", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.TimeMicrosConversion timeConversions_TimeMicrosConversion0 = new TimeConversions.TimeMicrosConversion();
      Schema schema0 = timeConversions_TimeMicrosConversion0.getRecommendedSchema();
      assertNull(schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.TimeMicrosConversion timeConversions_TimeMicrosConversion0 = new TimeConversions.TimeMicrosConversion();
      String string0 = timeConversions_TimeMicrosConversion0.adjustAndSetValue("", "PLx?3@B.}9VsRbKP(");
      assertEquals(" = PLx?3@B.}9VsRbKP(.truncatedTo(java.time.temporal.ChronoUnit.MICROS);", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.TimeMicrosConversion timeConversions_TimeMicrosConversion0 = new TimeConversions.TimeMicrosConversion();
      Class<LocalTime> class0 = timeConversions_TimeMicrosConversion0.getConvertedType();
      assertEquals(17, class0.getModifiers());
  }
}
