/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 11 15:43:04 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.Clock;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$TimestampNanosConversion_ESTest extends TimeConversions$TimestampNanosConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Instant instant0 = MockInstant.ofEpochSecond((-3548L), 0L);
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((String) null, "org.apache.avro.data.TimeConversions$TimestampNanosConversion", (String) null, true, (List<Schema.Field>) arrayList0);
      LogicalType logicalType0 = new LogicalType("Zv");
      Long long0 = timeConversions_TimestampNanosConversion0.toLong(instant0, schema0, logicalType0);
      assertEquals((-3548000000000L), (long)long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      System.setCurrentTimeMillis(1L);
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Clock clock0 = MockClock.systemDefaultZone();
      Instant instant0 = MockInstant.now(clock0);
      Instant instant1 = MockInstant.minusMillis(instant0, 477L);
      Instant instant2 = MockInstant.minusNanos(instant1, (-2605L));
      Schema schema0 = timeConversions_TimestampNanosConversion0.getRecommendedSchema();
      LogicalType logicalType0 = schema0.getLogicalType();
      Long long0 = timeConversions_TimestampNanosConversion0.toLong(instant2, schema0, logicalType0);
      assertEquals(523002605L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Class<Instant> class0 = timeConversions_TimestampNanosConversion0.getConvertedType();
      assertFalse(class0.isSynthetic());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      String string0 = timeConversions_TimestampNanosConversion0.getLogicalTypeName();
      assertEquals("timestamp-nanos", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      String string0 = timeConversions_TimestampNanosConversion0.adjustAndSetValue("timestamp-nanos", "timestamp-nanos");
      assertEquals("timestamp-nanos = timestamp-nanos.truncatedTo(java.time.temporal.ChronoUnit.NANOS);", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Schema schema0 = timeConversions_TimestampNanosConversion0.getRecommendedSchema();
      Long long0 = new Long(0L);
      LogicalType logicalType0 = schema0.getLogicalType();
      Instant instant0 = timeConversions_TimestampNanosConversion0.fromLong(long0, schema0, logicalType0);
      Long long1 = timeConversions_TimestampNanosConversion0.toLong(instant0, schema0, logicalType0);
      assertEquals(0L, (long)long1);
  }
}
