/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 11 15:42:37 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.LocalTime;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$TimeMillisConversion_ESTest extends TimeConversions$TimeMillisConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.TimeMillisConversion timeConversions_TimeMillisConversion0 = new TimeConversions.TimeMillisConversion();
      String string0 = timeConversions_TimeMillisConversion0.adjustAndSetValue("com.fasterxml.jackson.databind.ser.impl.SimpleFilterProvider", "com.fasterxml.jackson.databind.introspect.AnnotatedWithParams");
      assertEquals("com.fasterxml.jackson.databind.ser.impl.SimpleFilterProvider = com.fasterxml.jackson.databind.introspect.AnnotatedWithParams.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.TimeMillisConversion timeConversions_TimeMillisConversion0 = new TimeConversions.TimeMillisConversion();
      Schema schema0 = timeConversions_TimeMillisConversion0.getRecommendedSchema();
      assertNull(schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.TimeMillisConversion timeConversions_TimeMillisConversion0 = new TimeConversions.TimeMillisConversion();
      String string0 = timeConversions_TimeMillisConversion0.getLogicalTypeName();
      assertEquals("time-millis", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.TimeMillisConversion timeConversions_TimeMillisConversion0 = new TimeConversions.TimeMillisConversion();
      Class<LocalTime> class0 = timeConversions_TimeMillisConversion0.getConvertedType();
      assertFalse(class0.isEnum());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.TimeMillisConversion timeConversions_TimeMillisConversion0 = new TimeConversions.TimeMillisConversion();
      Integer integer0 = new Integer(0);
      Schema schema0 = Schema.createRecord("com.fasterxml.jackson.databind.introspect.AnnotatedWithParams", "lZzTbiw]Md!zDf.0)Y", "", false);
      LogicalType logicalType0 = new LogicalType("");
      LocalTime localTime0 = timeConversions_TimeMillisConversion0.fromInt(integer0, schema0, logicalType0);
      Integer integer1 = timeConversions_TimeMillisConversion0.toInt(localTime0, schema0, logicalType0);
      assertTrue(integer1.equals((Object)integer0));
  }
}
