/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 11 15:42:56 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.Instant;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$TimestampMicrosConversion_ESTest extends TimeConversions$TimestampMicrosConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Schema schema0 = Schema.createRecord((String) null, "${{Hn1KV`3sXj-", "${{Hn1KV`3sXj-", true);
      Instant instant0 = MockInstant.ofEpochSecond((-1053L));
      Long long0 = timeConversions_TimestampMicrosConversion0.toLong(instant0, schema0, (LogicalType) null);
      assertEquals((-1053000000L), (long)long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Long long0 = new Long(1370L);
      Schema schema0 = timeConversions_TimestampMicrosConversion0.getRecommendedSchema();
      LogicalType logicalType0 = new LogicalType("A,=w+/MUeKO");
      Instant instant0 = timeConversions_TimestampMicrosConversion0.fromLong(long0, schema0, logicalType0);
      Long long1 = timeConversions_TimestampMicrosConversion0.toLong(instant0, schema0, logicalType0);
      assertEquals(1370L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Long long0 = new Long((-1902L));
      Schema schema0 = Schema.createRecord((String) null, "${{Hn1KV`3sXj-", "${{Hn1KV`3sXj-", true);
      Instant instant0 = timeConversions_TimestampMicrosConversion0.fromLong(long0, schema0, (LogicalType) null);
      Long long1 = timeConversions_TimestampMicrosConversion0.toLong(instant0, schema0, (LogicalType) null);
      assertEquals((-1902L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      String string0 = timeConversions_TimestampMicrosConversion0.adjustAndSetValue("timestamp-micros", "timestamp-micros");
      assertEquals("timestamp-micros = timestamp-micros.truncatedTo(java.time.temporal.ChronoUnit.MICROS);", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Class<Instant> class0 = timeConversions_TimestampMicrosConversion0.getConvertedType();
      assertFalse(class0.isSynthetic());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      String string0 = timeConversions_TimestampMicrosConversion0.getLogicalTypeName();
      assertEquals("timestamp-micros", string0);
  }
}
