/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 25 15:25:19 GMT 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.apache.avro.NameValidator;
import org.apache.avro.ParseContext;
import org.apache.avro.Schema;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Schema$Parser_ESTest extends Schema$Parser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        schema_Parser0.parse("_ARD[D~!xoDr$qt`", stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unrecognized token '_ARD': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
         //  at [Source: (String)\"_ARD[D~!xoDr$qt`null\"; line: 1, column: 5]
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      boolean boolean0 = schema_Parser0.getValidateDefaults();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      ArrayList<Schema> arrayList0 = new ArrayList<Schema>(0);
      Schema schema0 = Schema.createUnion((List<Schema>) arrayList0);
      List<Schema> list0 = List.of(schema0);
      // Undeclared exception!
      try { 
        schema_Parser0.addTypes((Iterable<Schema>) list0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // You can only put a named schema into the context
         //
         verifyException("org.apache.avro.ParseContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      // Undeclared exception!
      try { 
        schema_Parser0.parseInternal("");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Cannot parse <null> schema
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      File file0 = MockFile.createTempFile("Y5>Kj~w", "Y5>Kj~w");
      // Undeclared exception!
      try { 
        schema_Parser0.parse(file0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Cannot parse <null> schema
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      assertTrue(schema_Parser0.getValidateDefaults());
      
      schema_Parser0.setValidateDefaults(false);
      assertFalse(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      Map<String, Schema> map0 = schema_Parser0.getTypes();
      Schema.Parser schema_Parser1 = schema_Parser0.addTypes(map0);
      assertTrue(schema_Parser1.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      InputStream inputStream0 = InputStream.nullInputStream();
      // Undeclared exception!
      try { 
        schema_Parser0.parse(inputStream0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Cannot parse <null> schema
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }
}
