/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 25 15:22:45 GMT 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.BooleanNode;
import com.fasterxml.jackson.databind.node.DoubleNode;
import com.fasterxml.jackson.databind.node.FloatNode;
import com.fasterxml.jackson.databind.node.IntNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.LongNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.ser.DefaultSerializerProvider;
import com.fasterxml.jackson.databind.util.TokenBuffer;
import java.io.File;
import java.io.InputStream;
import java.time.chrono.MinguoEra;
import java.util.ArrayDeque;
import java.util.Collection;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Set;
import java.util.Stack;
import java.util.Vector;
import org.apache.avro.LogicalType;
import org.apache.avro.NameValidator;
import org.apache.avro.ParseContext;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Schema_ESTest extends Schema_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("stri", schema0);
      schema_LockableArrayList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord("stri", "stri", "stri", true, (List<Schema.Field>) schema_LockableArrayList0);
      schema_Field0.addAlias((String) null);
      assertEquals(0, schema_Field0.pos());
      
      Schema schema2 = Schema.createFixed("stri", "stri", (String) null, 5);
      schema1.addAlias("stri", "stri");
      Schema.applyAliases(schema2, schema1);
      assertFalse(schema2.equals((Object)schema1));
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("stri", schema0);
      schema_LockableArrayList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord("stri", "stri", "stri", true, (List<Schema.Field>) schema_LockableArrayList0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertEquals(Schema.Type.STRING, schema2.getType());
      assertFalse(schema2.equals((Object)schema1));
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Schema schema0 = Schema.createFixed("pH", "type", "type", 14);
      schema0.addAlias("type", "type");
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertFalse(schema2.equals((Object)schema1));
      assertEquals("type", schema2.getDoc());
      assertSame(schema2, schema0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Schema schema0 = Schema.createFixed("type", "type", "type", 14);
      schema0.addAlias("type", "type");
      Schema schema1 = Protocol.SYSTEM_ERRORS;
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertTrue(schema2.equals((Object)schema1));
      assertNotSame(schema2, schema1);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Schema schema0 = Schema.createFixed("type", "type", "type", 12);
      schema0.addAlias("type", "type");
      Schema[] schemaArray0 = new Schema[0];
      Schema schema1 = Schema.createUnion(schemaArray0);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertNotSame(schema2, schema1);
      assertTrue(schema2.equals((Object)schema1));
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse("{\"type\":\"record\",\"fields\":[]}");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // No name in schema: {\"type\":\"record\",\"fields\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      // Undeclared exception!
      try { 
        schema_Parser0.parse("5");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Schema not yet supported: 5
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Schema schema0 = Schema.parse("{\"type\":\"enum\",\"name\":\"USE_GETTERS_AS_SETTERS\",\"namespace\":\"USE_GETTERS_AS_SETTERS\",\"doc\":\"USE_GETTERS_AS_SETTERS\",\"symbols\":[]}");
      assertEquals("USE_GETTERS_AS_SETTERS", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Schema schema0 = Schema.parse("{\n  \"type\" : \"fixed\",\n  \"name\" : \"type\",\n  \"namespace\" : \"type\",\n  \"doc\" : \"type\",\n  \"size\" : 16\n}");
      assertFalse(schema0.isUnion());
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse((InputStream) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Cannot parse <null> schema
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("stri", schema0);
      schema_LockableArrayList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord("stri", "stri", "stri", true, (List<Schema.Field>) schema_LockableArrayList0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      ObjectNode objectNode1 = objectNode0.put("stri", "stri");
      boolean boolean0 = schema1.isValidDefault(objectNode1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Schema schema0 = Schema.createMap((Schema) null);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      objectNode0.putNull("/Hc_uB,0");
      // Undeclared exception!
      try { 
        schema0.isValidDefault(objectNode0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Schema schema0 = Schema.createMap((Schema) null);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      Schema schema0 = Schema.create(schema_Type0);
      LongNode longNode0 = new LongNode(2644L);
      boolean boolean0 = schema0.isValidDefault(longNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.INT;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.BOOLEAN;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Schema schema0 = Schema.createFixed("ibn9V2", "ibn9V2", "ibn9V2", 512);
      FloatNode floatNode0 = FloatNode.valueOf(512);
      boolean boolean0 = schema0.isValidDefault(floatNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ArrayNode arrayNode0 = new ArrayNode(jsonNodeFactory0, 3800);
      boolean boolean0 = schema0.isValidDefault(arrayNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      Schema schema0 = Schema.createEnum("USE_GETTERS_AS_SETERS", "USE_GETTERS_AS_SETERS", "USE_GETTERS_AS_SETERS", (List<String>) stack0);
      BooleanNode booleanNode0 = BooleanNode.getTrue();
      boolean boolean0 = schema0.isValidDefault(booleanNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      boolean boolean0 = schema0.isValidDefault((JsonNode) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("m", schema0, "m", "m");
      assertEquals(Schema.Field.Order.ASCENDING, schema_Field0.order());
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer");
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Name schema_Name0 = new Schema.Name("com.fasterxml.jackson.databind.introspect.BasicBeanDescription", ".F");
      schema_Names0.put(schema_Name0, schema0);
      schema_Names0.put(schema_Name0, schema0);
      assertEquals("com.fasterxml.jackson.databind.introspect.BasicBeanDescription", schema_Name0.toString());
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Schema schema0 = Schema.createFixed("com.fasterxml.jacksondatabnd.deser.std.SdDelegatingDeserializer", "charOffset", "float", 512);
      Schema.Names schema_Names0 = new Schema.Names();
      Schema.Name schema_Name0 = new Schema.Name("com.fasterxml.jacksondatabnd.deser.std.SdDelegatingDeserializer", "com.fasterxml.jacksondatabnd.deser.std.SdDelegatingDeserializer");
      schema_Names0.put(schema_Name0, schema0);
      assertEquals("com.fasterxml.jacksondatabnd.deser.std.SdDelegatingDeserializer", schema_Name0.toString());
      
      boolean boolean0 = schema_Names0.contains(schema0);
      assertEquals("charOffset", schema0.getDoc());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      Schema schema0 = Schema.createFixed("ibn9V2", "ibn9V2", "ibn9V2", 512);
      boolean boolean0 = schema_Names0.contains(schema0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Names schema_Names0 = new Schema.Names("org.apache.avro.compiler.UnresolvedSchema_87");
      Schema.Name schema_Name0 = new Schema.Name("org.apache.avro.compiler.UnresolvedSchema_87", "o:;HPd6HU8?HD^");
      schema_Names0.put(schema_Name0, schema0);
      Schema schema1 = schema_Names0.get("org.apache.avro.compiler.UnresolvedSchema_87");
      assertFalse(schema1.isUnion());
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse("type", true);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'type': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
         //  at [Source: (String)\"type\"; line: 1, column: 5]
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse((String) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.core.JsonFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      String[] stringArray0 = new String[4];
      // Undeclared exception!
      try { 
        schema_Parser0.parse("c)j2;7`W;-RG.E7NUM", stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'c': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
         //  at [Source: (String)\"c)j2;7`W;-RG.E7NUMnullnullnullnull\"; line: 1, column: 2]
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      Schema.Parser schema_Parser0 = new Schema.Parser(nameValidator0);
      Schema[] schemaArray0 = new Schema[5];
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>(schemaArray0);
      // Undeclared exception!
      try { 
        schema_Parser0.addTypes((Iterable<Schema>) schema_LockableArrayList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.ParseContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Schema schema0 = Schema.createFixed("type", "type", "type", 12);
      schema0.addAlias("type", "type");
      Schema schema1 = Schema.createMap(schema0);
      LogicalType logicalType0 = new LogicalType("org.apache.avro.compiler.UnresolvedSchema_432");
      Schema schema2 = logicalType0.addToSchema(schema0);
      Schema schema3 = Schema.applyAliases(schema2, schema1);
      assertNotSame(schema3, schema2);
      assertTrue(schema3.equals((Object)schema2));
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>(13);
      Schema schema1 = Schema.createUnion((List<Schema>) schema_LockableArrayList0);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertFalse(schema2.equals((Object)schema0));
      assertSame(schema2, schema1);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertSame(schema1, schema0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema[] schemaArray0 = new Schema[9];
      schemaArray0[0] = schema0;
      schemaArray0[1] = schema0;
      // Undeclared exception!
      try { 
        Schema.createUnion(schemaArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Duplicate in union:string
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema[] schemaArray0 = new Schema[1];
      schemaArray0[0] = schema0;
      // Undeclared exception!
      try { 
        Schema.createUnion(schemaArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Nameless in union:[{\"type\":\"record\",\"fields\":[]}]
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema[] schemaArray0 = new Schema[2];
      schemaArray0[0] = schema0;
      // Undeclared exception!
      try { 
        Schema.createUnion(schemaArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Schema schema0 = Schema.createFixed("com.fasterxml.jacksondatabnd.deser.std.SdDelegatingDeserializer", "com.fasterxml.jacksondatabnd.deser.std.SdDelegatingDeserializer", "com.fasterxml.jacksondatabnd.deser.std.SdDelegatingDeserializer", 14);
      Schema schema1 = Schema.createArray(schema0);
      schema1.addProp("com.fasterxml.jacksondatabnd.deser.std.SdDelegatingDeserializer", "fixed");
      Schema schema2 = Schema.createArray(schema0);
      Schema schema3 = Schema.applyAliases(schema1, schema2);
      assertFalse(schema3.equals((Object)schema2));
      assertSame(schema3, schema1);
      assertFalse(schema0.equals((Object)schema2));
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.createArray(schema0);
      Schema schema3 = Schema.applyAliases(schema1, schema2);
      assertFalse(schema3.equals((Object)schema0));
      assertTrue(schema3.equals((Object)schema2));
      assertFalse(schema0.equals((Object)schema2));
      assertNotSame(schema3, schema2);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Schema schema0 = Schema.createRecord("type", "type", "type", false);
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.createArray(schema1);
      // Undeclared exception!
      try { 
        Schema.applyAliases(schema1, schema2);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Schema fields not set yet
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      List<String> list0 = List.of("pH");
      Schema schema0 = Schema.createEnum("De", "com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer", "com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer", list0);
      // Undeclared exception!
      try { 
        schema0.getValueType();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a map: {\"type\":\"enum\",\"name\":\"De\",\"namespace\":\"com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer\",\"doc\":\"com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer\",\"symbols\":[\"pH\"]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema schema0 = Schema.createEnum("-)L&pNEb.USE_GETTERS_AS_SETTERS", (String) null, "com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder$Linked", (List<String>) schema_LockableArrayList0);
      // Undeclared exception!
      try { 
        schema0.getFixedSize();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not fixed: {\"type\":\"enum\",\"name\":\"USE_GETTERS_AS_SETTERS\",\"namespace\":\"-)L&pNEb\",\"symbols\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      Schema schema0 = Schema.createEnum("USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", (List<String>) stack0);
      stack0.add("USE_GETTERS_AS_SETTERS");
      Schema schema1 = Schema.createEnum("USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", (List<String>) stack0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertFalse(schema2.equals((Object)schema1));
      assertSame(schema2, schema0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Schema schema0 = Schema.createEnum("com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter", "type", "type", (List<String>) linkedList0);
      Schema schema1 = Schema.createEnum("I", "Lx\"Ag_A^|h", (String) null, (List<String>) linkedList0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertFalse(schema2.equals((Object)schema1));
      assertEquals("type", schema2.getDoc());
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Schema schema0 = Schema.createFixed("type", "type", "type", 14);
      schema0.addAlias("type", "type");
      Schema schema1 = Schema.createEnum("type", "oykHm", "oykHm", (List<String>) linkedList0);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertEquals("oykHm", schema2.getDoc());
      assertSame(schema2, schema1);
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      vector0.add("USE_GETTERS_AS_SETTERS");
      Schema schema0 = Schema.createEnum("USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", (List<String>) vector0);
      boolean boolean0 = schema0.hasEnumSymbol("USE_GETTERS_AS_SETTERS");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      Schema schema0 = Schema.createEnum("USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", (List<String>) vector0);
      boolean boolean0 = schema0.hasEnumSymbol("USE_GETTERS_AS_SETTERS");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      vector0.add("USE_GETTERS_AS_SETTERS");
      Schema schema0 = Schema.createEnum("USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", (List<String>) vector0, "USE_GETTERS_AS_SETTERS");
      assertFalse(schema0.isUnion());
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      // Undeclared exception!
      try { 
        Schema.createEnum("USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", (List<String>) vector0, "USE_GETTERS_AS_SETTERS");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The Enum Default: USE_GETTERS_AS_SETTERS is not in the enum symbol set: []
         //
         verifyException("org.apache.avro.Schema$EnumSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      String[] stringArray0 = new String[4];
      stringArray0[0] = "fixed";
      stringArray0[1] = "fixed";
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>(stringArray0);
      // Undeclared exception!
      try { 
        Schema.createEnum("fixed", "fixed", "fixed", (List<String>) schema_LockableArrayList0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Duplicate enum symbol: fixed
         //
         verifyException("org.apache.avro.Schema$EnumSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Schema schema0 = Schema.createRecord("com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer", "org.apache.avro.Schema$BytesSchema", "com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer", false);
      // Undeclared exception!
      try { 
        schema0.getValueType();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a map: {\"type\":\"record\",\"name\":\"StdDelegatingDeserializer\",\"namespace\":\"com.fasterxml.jackson.databind.deser.std\",\"doc\":\"org.apache.avro.Schema$BytesSchema\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema0 = parseContext0.find("lN[`NI 5S", "ibn9V2");
      Schema[] schemaArray0 = new Schema[8];
      schemaArray0[0] = schema0;
      schemaArray0[1] = schema0;
      schemaArray0[2] = schema0;
      schemaArray0[3] = schema0;
      schemaArray0[4] = schema0;
      schemaArray0[5] = schema0;
      schemaArray0[6] = schema0;
      schemaArray0[7] = schema0;
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>(schemaArray0);
      Vector<Schema> vector0 = new Vector<Schema>(schema_LockableArrayList0);
      String string0 = schema0.toString((Collection<Schema>) vector0, false);
      //  // Unstable assertion: assertEquals("\"org.apache.avro.compiler.UnresolvedSchema_134\"", string0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = parseContext0.find("DESCENDING", "org.apache.avro.Schema$Field");
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0);
      schema_LockableArrayList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord("DESCENDING", "org.apache.avro.Schema$Field", "'7.[N;", false, (List<Schema.Field>) schema_LockableArrayList0);
      int int0 = schema1.computeHash();
      //  // Unstable assertion: assertEquals((-1613569898), int0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema.applyAliases(schema0, schema0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord("e.e", ") does not override copy(); it has to", "fpA|9]8{o@@D5u>P,", false, (List<Schema.Field>) schema_LockableArrayList0);
      // Undeclared exception!
      try { 
        schema0.setFields(schema_LockableArrayList0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Fields are already set
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      schema0.hasFields();
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Schema schema0 = Schema.createRecord("type", "type", "type", false);
      Schema schema1 = Schema.createArray(schema0);
      // Undeclared exception!
      try { 
        Schema.applyAliases(schema1, schema0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Schema fields not set yet
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Schema schema0 = Schema.createRecord("map", "hWS+vWn1V<aQ", "map", false);
      // Undeclared exception!
      try { 
        schema0.getField("map");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Schema fields not set yet
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      schema0.getField("lK!7 SlJ>(7aZo v");
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      SerializationFeature serializationFeature0 = SerializationFeature.WRITE_ENUMS_USING_TO_STRING;
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(serializationFeature0, (Object) null);
      boolean boolean0 = schema_SeenPair0.equals(serializationFeature0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Schema schema0 = Schema.createMap((Schema) null);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(jsonNodeFactory0, schema0);
      boolean boolean0 = schema_SeenPair0.equals(schema_SeenPair0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      schema0.addAlias((String) null, "order");
      schema0.getAliases();
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Schema schema0 = Schema.createFixed("com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer", "qv;^rQZ9R", "De", 14);
      schema0.addAlias((String) null, "De");
      Set<String> set0 = schema0.getAliases();
      assertEquals("qv;^rQZ9R", schema0.getDoc());
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      Schema schema0 = Schema.createEnum("USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", (List<String>) vector0);
      schema0.addAlias("null", "null");
      Set<String> set0 = schema0.getAliases();
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      ParseContext parseContext0 = new ParseContext();
      parseContext0.resolve(schema0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Schema schema0 = Schema.createFixed("type", "type", "type", 14);
      schema0.addAlias("type", "type");
      schema0.addAlias("type", "type");
      assertEquals(Schema.Type.FIXED, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Schema schema0 = Schema.createFixed((String) null, (String) null, (String) null, 25);
      schema0.addAlias((String) null, (String) null);
      // Undeclared exception!
      try { 
        schema0.getValueType();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a map: {\"type\":\"fixed\",\"size\":25,\"aliases\":[null]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Schema schema0 = Schema.createFixed("type", "type", "type", 14);
      schema0.addAlias("type", "type");
      // Undeclared exception!
      try { 
        schema0.getValueType();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a map: {\"type\":\"fixed\",\"name\":\"type\",\"namespace\":\"type\",\"doc\":\"type\",\"size\":14,\"aliases\":[\"type\"]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Schema.Name schema_Name0 = new Schema.Name((String) null, (String) null);
      // Undeclared exception!
      try { 
        schema_Name0.writeName("5]\"~-gG%n:}=#P5", (JsonGenerator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$Name", e);
      }
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      Schema schema0 = Schema.createEnum("USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", (List<String>) vector0);
      HashSet<String> hashSet0 = new HashSet<String>();
      DefaultSerializerProvider.Impl defaultSerializerProvider_Impl0 = new DefaultSerializerProvider.Impl();
      ObjectMapper objectMapper0 = new ObjectMapper();
      TokenBuffer tokenBuffer0 = defaultSerializerProvider_Impl0.bufferForValueConversion((ObjectCodec) objectMapper0);
      schema0.toJson(hashSet0, "USE_GETTERS_AS_SETTERS", tokenBuffer0);
      assertFalse(tokenBuffer0.isEmpty());
      assertEquals(1, hashSet0.size());
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Schema.Name schema_Name0 = new Schema.Name((String) null, "-Infinity");
      boolean boolean0 = schema_Name0.equals("-Infinity");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      Schema schema0 = schema_Names0.get("items");
      assertNull(schema0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("ENUM", schema0);
      boolean boolean0 = schema_Field0.equals("ENUM");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("stri", schema0);
      Set<String> set0 = schema_Field0.aliases();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      List<String> list0 = List.of("pH");
      Schema schema0 = Schema.createEnum("De", "com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer", "com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer", list0);
      Schema.Field schema_Field0 = new Schema.Field("De", schema0, "pH");
      schema_Field0.addAlias("De");
      Set<String> set0 = schema_Field0.aliases();
      assertEquals("com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer", schema0.getDoc());
      assertEquals("pH", schema_Field0.doc());
      assertTrue(set0.contains("De"));
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      List<String> list0 = List.of("pH");
      Schema schema0 = Schema.createEnum("De", "com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer", "com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer", list0);
      Schema.Field schema_Field0 = new Schema.Field("De", schema0, "pH");
      schema_Field0.addAlias("De");
      schema_Field0.addAlias("?9)CW");
      assertEquals("com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer", schema0.getDoc());
      assertEquals("pH", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      LongNode longNode0 = new LongNode((-813L));
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("items", schema0, "items", longNode0, false, schema_Field_Order0);
      boolean boolean0 = schema_Field0.hasDefaultValue();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("K\".&Z", (Schema) null, "K\".&Z", "K\".&Z", schema_Field_Order0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Illegal character in: K\".&Z
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("stri", schema0);
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema schema1 = Schema.createMap(schema0);
      boolean boolean0 = schema1.equalCachedHash(schema0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      Schema schema0 = Schema.createEnum("org.apacLe.avro.idl.unresolved.name", "org.apacLe.avro.idl.unresolved.name", "org.apacLe.avro.idl.unresolved.name", (List<String>) vector0);
      LinkedHashSet<Schema> linkedHashSet0 = new LinkedHashSet<Schema>();
      linkedHashSet0.add(schema0);
      Schema schema1 = Schema.createEnum("org.apacLe.avro.idl.unresolved.name", "org.apacLe.avro.idl.unresolved.name", "org.apacLe.avro.idl.unresolved.name", (List<String>) vector0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertTrue(schema2.equals((Object)schema1));
      assertTrue(schema1.equals((Object)schema0));
      assertNotSame(schema2, schema1);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      LinkedHashSet<Schema> linkedHashSet0 = new LinkedHashSet<Schema>();
      boolean boolean0 = linkedHashSet0.add(schema0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      MinguoEra minguoEra0 = MinguoEra.ROC;
      boolean boolean0 = schema0.equals(minguoEra0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.parse("[ \"string\" ]");
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertTrue(schema2.equals((Object)schema1));
      assertNotSame(schema2, schema1);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      LinkedHashSet<Schema> linkedHashSet0 = new LinkedHashSet<Schema>();
      String string0 = schema0.toString((Collection<Schema>) linkedHashSet0, true);
      assertEquals("[ \"string\" ]", string0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      // Undeclared exception!
      try { 
        schema0.toString((Collection<Schema>) null, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$ArraySchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.ENUM;
      // Undeclared exception!
      try { 
        Schema.create(schema_Type0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Can't create a: ENUM
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.ARRAY;
      String string0 = schema_Type0.getName();
      assertEquals("array", string0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.FLOAT;
      Schema schema0 = Schema.create(schema_Type0);
      LongNode longNode0 = LongNode.valueOf(2644L);
      boolean boolean0 = schema0.isValidDefault(longNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.INT;
      Schema schema0 = Schema.create(schema_Type0);
      LongNode longNode0 = new LongNode(2644L);
      boolean boolean0 = schema0.isValidDefault(longNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.BYTES;
      Schema schema0 = Schema.create(schema_Type0);
      LongNode longNode0 = LongNode.valueOf(2644L);
      boolean boolean0 = schema0.isValidDefault(longNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.NULL;
      Schema schema0 = Schema.create(schema_Type0);
      LongNode longNode0 = LongNode.valueOf(2644L);
      boolean boolean0 = schema0.isValidDefault(longNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("[ \"string\" ]");
      Schema schema0 = schema_Names0.get("boolean");
      //  // Unstable assertion: assertNull(schema0);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.DOUBLE;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      Schema schema0 = Schema.create(schema_Type0);
      BooleanNode booleanNode0 = BooleanNode.TRUE;
      boolean boolean0 = schema0.isValidDefault(booleanNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("stri", schema0);
      schema_LockableArrayList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord("stri", "stri", "stri", true, (List<Schema.Field>) schema_LockableArrayList0);
      schema_Field0.addAlias((String) null);
      Schema schema2 = Schema.createArray(schema1);
      Schema schema3 = Schema.applyAliases(schema2, schema1);
      assertSame(schema3, schema2);
      assertEquals(Schema.Type.ARRAY, schema3.getType());
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      // Undeclared exception!
      try { 
        schema0.hashCode();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$ArraySchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Schema schema0 = Schema.createFixed("type", "type", "type", 12);
      int int0 = schema0.computeHash();
      //  // Unstable assertion: assertEquals(1667771290, int0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Schema schema0 = Schema.createFixed("type", "type", "type", 12);
      schema0.addAlias("type", "type");
      Schema schema1 = Schema.createMap(schema0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertNotSame(schema2, schema0);
      assertTrue(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Schema schema0 = Schema.createFixed("type", "type", "type", 12);
      schema0.addAlias("type");
      assertEquals(Schema.Type.FIXED, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      String string0 = schema0.getFullName();
      assertEquals("union[string]", string0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      IntNode intNode0 = new IntNode((-3727));
      boolean boolean0 = schema0.isValidDefault(intNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Integer integer0 = schema0.getIndexNamed((String) null);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      LogicalType logicalType0 = new LogicalType(", new = ");
      // Undeclared exception!
      try { 
        logicalType0.addToSchema(schema0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Can't set properties on a union: [\"string\"]
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      String string0 = schema_Names0.space();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      schema_Names0.space("ibn9V2");
      assertEquals("ibn9V2", schema_Names0.space());
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      // Undeclared exception!
      try { 
        schema_Names0.add((Schema) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$Names", e);
      }
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      boolean boolean0 = schema_Parser0.getValidateDefaults();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      ArrayDeque<Schema> arrayDeque0 = new ArrayDeque<Schema>();
      Schema.Parser schema_Parser1 = schema_Parser0.addTypes((Iterable<Schema>) arrayDeque0);
      assertTrue(schema_Parser1.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      // Undeclared exception!
      try { 
        schema_Parser0.parseInternal("`6z2O&Kl$`");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unexpected character ('`' (code 96)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
         //  at [Source: (String)\"`6z2O&Kl$`\"; line: 1, column: 2]
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      Schema.Parser schema_Parser0 = new Schema.Parser(nameValidator0);
      assertTrue(schema_Parser0.getValidateDefaults());
      
      schema_Parser0.setValidateDefaults(false);
      assertFalse(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      schema_Parser0.getTypes();
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer");
      Schema.Name schema_Name0 = new Schema.Name("com.fasterxml.jackson.databind.introspect.BasicBeanDescription", ".F");
      schema_Names0.put(schema_Name0, (Schema) null);
      Schema schema0 = Schema.createMap((Schema) null);
      // Undeclared exception!
      try { 
        schema_Names0.put(schema_Name0, schema0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Can't redefine: com.fasterxml.jackson.databind.introspect.BasicBeanDescription
         //
         verifyException("org.apache.avro.Schema$Names", e);
      }
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      Schema schema0 = Schema.createFixed("pH", "type", "type", 14);
      // Undeclared exception!
      try { 
        schema0.fieldsToJson((Set<String>) null, "type", (JsonGenerator) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a record: {\"type\":\"fixed\",\"name\":\"pH\",\"namespace\":\"type\",\"doc\":\"type\",\"size\":14}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getFields();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      Schema schema0 = Schema.createFixed("type", "type", "type", 14);
      schema0.addAlias("type", "type");
      Stack<String> stack0 = new Stack<String>();
      Schema schema1 = Schema.createEnum("type", "type", "type", (List<String>) stack0);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertTrue(schema2.equals((Object)schema1));
      assertNotSame(schema2, schema1);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.hasEnumSymbol("MA");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not an enum: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Vector<Schema.Field> vector0 = new Vector<Schema.Field>();
      // Undeclared exception!
      try { 
        schema0.setFields(vector0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse((File) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.addAlias("org.apache.avro.Schema$SeenPair", "org.apache.avro.Schema$SeenPair");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a named type: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      boolean boolean0 = Schema.getValidateDefaults();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getEnumDefault();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not an enum: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.addAlias("org.apache.avro.compiler.UnresolvedSchema_197");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a named type: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      String string0 = schema0.getDoc();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("stri", schema0);
      schema_LockableArrayList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord("stri", "stri", "stri", true, (List<Schema.Field>) schema_LockableArrayList0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      Short short0 = new Short((short)7);
      objectNode0.put("stri", short0);
      boolean boolean0 = schema1.isValidDefault(objectNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getElementType();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not an array: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.getNamespace();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a named type: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.hasFields();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a record: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parseJsonToObject("v_C\"#");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'v_C': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
         //  at [Source: (String)\"v_C\"#\"; line: 1, column: 4]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.getTypes();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getEnumSymbols();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not an enum: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      // Undeclared exception!
      try { 
        schema0.getIndexNamed("null");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$ArraySchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getAliases();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a named type: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.getField("stri");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a record: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      Schema.setValidateDefaults(false);
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Object object0 = schema0.writeReplace();
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.isError();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getEnumOrdinal("RYs]pJ/L$,kaqW'");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not an enum: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse("{\"type\":\"record\",\"name\":\"UnresolvedSchema_497\",\"namespace\":\"org.apache.avro.compiler\",\"doc\":\"unresolved schema\",\"fields\":[],\"org.apache.avro.idl.unresolved.name\":\"lN[`NI 5S. @!&QkVvF8yzi,4h#\"}");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Undefined schema: lN[`NI 5S. @!&QkVvF8yzi,4h#
         //
         verifyException("org.apache.avro.util.SchemaResolver$ResolvingVisitor", e);
      }
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      Schema schema0 = Schema.createEnum("USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", "USE_GETTERS_AS_SETTERS", (List<String>) vector0);
      LinkedHashSet<Schema> linkedHashSet0 = new LinkedHashSet<Schema>();
      linkedHashSet0.add(schema0);
      String string0 = schema0.toString((Collection<Schema>) linkedHashSet0, false);
      assertEquals("\"USE_GETTERS_AS_SETTERS.USE_GETTERS_AS_SETTERS\"", string0);
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      LongNode longNode0 = new LongNode((-813L));
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("items", schema0, "lk/i'Q#MGTgH?jW:U", longNode0, false, schema_Field_Order0);
      int int0 = schema_Field0.pos();
      assertEquals((-1), int0);
      assertEquals("lk/i'Q#MGTgH?jW:U", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      DoubleNode doubleNode0 = DoubleNode.valueOf(0.0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("Collection", schema0, "Collection", doubleNode0, false, schema_Field_Order0);
      Object object0 = schema_Field0.defaultVal();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("stri", schema0);
      schema_LockableArrayList0.add(schema_Field0);
      schema_LockableArrayList0.add(schema_Field0);
      // Undeclared exception!
      try { 
        Schema.createRecord("stri", "stri", "stri", true, (List<Schema.Field>) schema_LockableArrayList0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Field already used: stri type:STRING pos:0
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("stri", schema0);
      schema_LockableArrayList0.add(schema_Field0);
      assertEquals((-1), schema_Field0.pos());
      
      Schema schema1 = Schema.createRecord("stri", "stri", "stri", true, (List<Schema.Field>) schema_LockableArrayList0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      boolean boolean0 = schema1.isValidDefault(objectNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("stri", schema0);
      schema_LockableArrayList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord("stri", "stri", "stri", true, (List<Schema.Field>) schema_LockableArrayList0);
      // Undeclared exception!
      try { 
        schema1.getValueType();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a map: {\"type\":\"error\",\"name\":\"stri\",\"namespace\":\"stri\",\"doc\":\"stri\",\"fields\":[{\"name\":\"stri\",\"type\":\"string\"}]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>(958);
      HashSet<String> hashSet0 = new HashSet<String>();
      // Undeclared exception!
      try { 
        schema_LockableArrayList0.addAll(958, (Collection<? extends String>) hashSet0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 958, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      boolean boolean0 = schema_LockableArrayList0.addAll((Collection<? extends Schema.Field>) schema_LockableArrayList0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      boolean boolean0 = schema_LockableArrayList0.remove((Object) "DESCENDING");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test146()  throws Throwable  {
      Schema.LockableArrayList<Object> schema_LockableArrayList0 = new Schema.LockableArrayList<Object>();
      // Undeclared exception!
      try { 
        schema_LockableArrayList0.remove(2761);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test147()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      ArrayDeque<Schema> arrayDeque0 = new ArrayDeque<Schema>();
      boolean boolean0 = schema_LockableArrayList0.removeAll(arrayDeque0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test148()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      PriorityQueue<String> priorityQueue0 = new PriorityQueue<String>();
      boolean boolean0 = schema_LockableArrayList0.retainAll(priorityQueue0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test149()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      schema_LockableArrayList0.clear();
      assertTrue(schema_LockableArrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test150()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createMap(schema0);
      int int0 = schema1.computeHash();
      //  // Unstable assertion: assertEquals((-622455298), int0);
  }

  @Test(timeout = 4000)
  public void test151()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      schema0.addAlias((String) null, (String) null);
      Schema schema1 = Schema.createMap(schema0);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertSame(schema2, schema1);
      assertEquals(Schema.Type.MAP, schema2.getType());
  }
}
