/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 25 15:24:07 GMT 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.FloatNode;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Schema$Field_ESTest extends Schema$Field_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("CIXmYaEFkIU", schema0, "CIXmYaEFkIU");
      Schema.Field schema_Field1 = new Schema.Field("CIXmYaEFkIU", schema0, "URI", "URI");
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertFalse(boolean0);
      assertFalse(schema_Field1.equals((Object)schema_Field0));
      assertEquals((-1), schema_Field1.pos());
      assertEquals("URI", schema_Field1.doc());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("CIXmYaEFkIU", schema0, "CIXmYaEFkIU");
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertTrue(schema_Field1.equals((Object)schema_Field0));
      
      schema_Field1.addProp("CIXmYaEFkIU", "CIXmYaEFkIU");
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("CIXmYaEFkIU", schema0, "CIXmYaEFkIU");
      Schema schema1 = Schema.createArray(schema0);
      Schema.Field schema_Field1 = new Schema.Field("CIXmYaEFkIU", schema1, "CIXmYaEFkIU");
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertFalse(boolean0);
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("CIXmYaEFkIU", schema0, "CIXmYaEFkIU");
      Schema.Field schema_Field1 = new Schema.Field("URI", schema0, "URI");
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertEquals((-1), schema_Field1.pos());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("CIXmYaEFkIU", schema0, "CIXmYaEFkIU");
      boolean boolean0 = schema_Field0.equals("CIXmYaEFkIU");
      assertEquals((-1), schema_Field0.pos());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("CIXmYaEFkIU", schema0, "l>rtf,r]Nl-(N*0");
      boolean boolean0 = schema_Field0.equals(schema_Field0);
      assertEquals("l>rtf,r]Nl-(N*0", schema_Field0.doc());
      assertTrue(boolean0);
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("out", schema0, "out", "out", schema_Field_Order0);
      Schema.Field schema_Field1 = new Schema.Field("out", schema0, "out");
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertFalse(boolean0);
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("CIXmYaEFkIU", schema0, "CIXmYaEFkIU");
      schema_Field0.aliases();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FloatNode floatNode0 = new FloatNode(3550.7805F);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Schema schema0 = Schema.createEnum("D", "D", "D", (List<String>) linkedList0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("D", schema0, "D", floatNode0, false, schema_Field_Order0);
      schema_Field0.addAlias("D");
      Set<String> set0 = schema_Field0.aliases();
      assertTrue(set0.contains("D"));
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("CIXmYaIU", schema0, "CIXmYaIU");
      schema_Field0.addAlias("CIXmYaIU");
      schema_Field0.addAlias("CIXmYaIU");
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("out", schema0, "out", "out", schema_Field_Order0);
      boolean boolean0 = schema_Field0.hasDefaultValue();
      assertEquals((-1), schema_Field0.pos());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("ASCENDING", schema0);
      boolean boolean0 = schema_Field0.hasDefaultValue();
      assertFalse(boolean0);
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("", schema0, "", object0, schema_Field_Order0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Empty name
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("?rh?na}Hx8&&#`t3[kX", schema0, "?rh?na}Hx8&&#`t3[kX", object0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Illegal initial character: ?rh?na}Hx8&&#`t3[kX
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("CIXmYaEFkIU", schema0, "CIXmYaEFkIU");
      schema_Field0.addAlias("CIXmYaEFkIU");
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("out", schema0, "out", "out", schema_Field_Order0);
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertTrue(boolean0);
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      FloatNode floatNode0 = FloatNode.valueOf(3550.7805F);
      Vector<String> vector0 = new Vector<String>();
      Schema schema0 = Schema.createEnum("D", "D", "D", (List<String>) vector0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("D", schema0, "D", floatNode0, false, schema_Field_Order0);
      int int0 = schema_Field0.pos();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("CIXmYaEFkIU", schema0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field1 = new Schema.Field("CIXmYaEFkIU", schema0, (String) null, (JsonNode) null, true, schema_Field_Order0);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertFalse(boolean0);
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("CIXmYaEFkIU", schema0, "CIXmYaEFkIU");
      schema_Field0.hashCode();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      FloatNode floatNode0 = new FloatNode(3550.7805F);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Schema schema0 = Schema.createEnum("D", "D", "D", (List<String>) linkedList0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("D", schema0, "D", floatNode0, false, schema_Field_Order0);
      schema_Field0.doc();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("UnresolvedSchema", schema0, "UnresolvedSchema");
      List<Schema.Field> list0 = List.of(schema_Field0, schema_Field0, schema_Field0, schema_Field0, schema_Field0, schema_Field0, schema_Field0, schema_Field0, schema_Field0, schema_Field0);
      // Undeclared exception!
      try { 
        Schema.createRecord("UnresolvedSchema", "UnresolvedSchema", "CIXmYaEFkIU", true, list0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Field already used: UnresolvedSchema type:STRING pos:0
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      FloatNode floatNode0 = new FloatNode(3550.7805F);
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("D", schema0, "D", floatNode0, false, schema_Field_Order0);
      schema_Field0.defaultValue();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("CIXmYaEFkIU", schema0, "CIXmYaEFkIU");
      schema_Field0.defaultVal();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      FloatNode floatNode0 = new FloatNode(3550.7805F);
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("D", schema0, "D", floatNode0, false, schema_Field_Order0);
      schema_Field0.schema();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      FloatNode floatNode0 = FloatNode.valueOf(3545.79F);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Schema schema0 = Schema.createEnum("D", "D", "D", (List<String>) linkedList0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("D", schema0, "D", floatNode0, false, schema_Field_Order0);
      schema_Field0.order();
      assertEquals((-1), schema_Field0.pos());
  }
}
