/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 25 14:33:46 GMT 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.avro.Schema;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Schema$SeenPair_ESTest extends Schema$SeenPair_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Object object0 = new Object();
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(object0, object0);
      Schema.SeenPair schema_SeenPair1 = new Schema.SeenPair(object0, schema_SeenPair0);
      boolean boolean0 = schema_SeenPair1.equals(schema_SeenPair0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object object0 = new Object();
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(object0, object0);
      Object object1 = new Object();
      Schema.SeenPair schema_SeenPair1 = new Schema.SeenPair(object1, schema_SeenPair0);
      boolean boolean0 = schema_SeenPair0.equals(schema_SeenPair1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Object object0 = new Object();
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(object0, object0);
      boolean boolean0 = schema_SeenPair0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Object object0 = new Object();
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(object0, object0);
      boolean boolean0 = schema_SeenPair0.equals(schema_SeenPair0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Object object0 = new Object();
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(object0, object0);
      schema_SeenPair0.hashCode();
  }
}
