/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 25 14:32:31 GMT 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import org.apache.avro.ParseContext;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Schema$Field_ESTest extends Schema$Field_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.withExactBigDecimals(false);
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0, "", objectNode0, false, schema_Field_Order0);
      Schema.Field schema_Field1 = new Schema.Field("CF", schema0);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertFalse(boolean0);
      assertEquals("", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0);
      Schema.Field schema_Field1 = new Schema.Field("CF", schema0, "?Pv:tMjdnrUi,#q");
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertTrue(boolean0);
      assertEquals("?Pv:tMjdnrUi,#q", schema_Field1.doc());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.withExactBigDecimals(false);
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0, "CF", objectNode0, false, schema_Field_Order0);
      schema_Field0.addProp("CF", "CF");
      Schema.Field schema_Field1 = new Schema.Field("CF", schema0, "CF", objectNode0, false, schema_Field_Order0);
      boolean boolean0 = schema_Field1.equals(schema_Field0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.withExactBigDecimals(false);
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0, "CF", objectNode0, false, schema_Field_Order0);
      Schema.Field.Order schema_Field_Order1 = Schema.Field.Order.IGNORE;
      Schema.Field schema_Field1 = new Schema.Field("CF", schema0, "CF", objectNode0, false, schema_Field_Order1);
      boolean boolean0 = schema_Field1.equals(schema_Field0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema schema1 = Schema.createRecord("IGNORE", "IGNORE", "IGNORE", false, (List<Schema.Field>) arrayList0);
      Schema.Field schema_Field0 = new Schema.Field("IGNORE", schema0, "IGNORE");
      Schema.Field schema_Field1 = new Schema.Field("IGNORE", schema1);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("IGNORE", schema0, "IGNORE");
      Schema.Field schema_Field1 = new Schema.Field("CF", schema0);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.withExactBigDecimals(false);
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0, "CF", objectNode0, false, schema_Field_Order0);
      Schema.Field schema_Field1 = new Schema.Field("CF", schema0);
      boolean boolean0 = schema_Field1.equals(schema_Field0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.withExactBigDecimals(false);
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0, "CF", objectNode0, false, schema_Field_Order0);
      boolean boolean0 = schema_Field0.equals(schema_Field0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.withExactBigDecimals(false);
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0, "CF", objectNode0, false, schema_Field_Order0);
      boolean boolean0 = schema_Field0.equals(objectNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("IGNORE", "IGNORE");
      Schema.Field schema_Field0 = new Schema.Field("IGNORE", schema0);
      Set<String> set0 = schema_Field0.aliases();
      assertFalse(set0.contains("IGNORE"));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0);
      schema_Field0.addAlias("CF");
      Set<String> set0 = schema_Field0.aliases();
      assertTrue(set0.contains("CF"));
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.withExactBigDecimals(false);
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0, "CF", objectNode0, false, schema_Field_Order0);
      schema_Field0.addAlias("-");
      schema_Field0.addAlias("CF");
      assertEquals("CF", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.withExactBigDecimals(false);
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0, "", objectNode0, false, schema_Field_Order0);
      boolean boolean0 = schema_Field0.hasDefaultValue();
      assertTrue(boolean0);
      assertEquals("", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0);
      boolean boolean0 = schema_Field0.hasDefaultValue();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("VCYe|`+Hz", (Schema) null, "VCYe|`+Hz", object0, schema_Field_Order0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Illegal character in: VCYe|`+Hz
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("Order cannot be null", (Schema) null, "Order cannot be null", (Object) null, schema_Field_Order0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Illegal character in: Order cannot be null
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Protocol protocol0 = new Protocol("", "", "");
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("", protocol0.SYSTEM_ERROR, "", object0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Empty name
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("", schema0, "", "");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Empty name
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0);
      schema_Field0.addAlias("");
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertFalse(schema_Field1.hasDefaultValue());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("IGNORE", schema0);
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertTrue(schema_Field1.equals((Object)schema_Field0));
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("IGNORE", "IGNORE");
      Schema.Field schema_Field0 = new Schema.Field("IGNORE", schema0);
      int int0 = schema_Field0.pos();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("IGNORE", "IGNORE");
      Schema.Field schema_Field0 = new Schema.Field("IGNORE", schema0);
      Object object0 = schema_Field0.defaultVal();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("IGNORE", "IGNORE");
      Schema.Field schema_Field0 = new Schema.Field("IGNORE", schema0);
      schema_Field0.hashCode();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.withExactBigDecimals(false);
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0, "CF", objectNode0, false, schema_Field_Order0);
      String string0 = schema_Field0.doc();
      assertEquals("CF", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("IGNORE", "IGNORE");
      Schema.Field schema_Field0 = new Schema.Field("IGNORE", schema0);
      String string0 = schema_Field0.toString();
      assertEquals("IGNORE type:RECORD pos:-1", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema.Field schema_Field0 = new Schema.Field("IGNORE", schema0);
      arrayList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord("IGNORE", "IGNORE", "IGNORE", false, (List<Schema.Field>) arrayList0);
      assertFalse(schema1.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.withExactBigDecimals(false);
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0, "CF", objectNode0, false, schema_Field_Order0);
      schema_Field0.defaultValue();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("CF", schema0, "", objectNode0, false, schema_Field_Order0);
      schema_Field0.schema();
      assertEquals((-1), schema_Field0.pos());
      assertEquals("", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.withExactBigDecimals(false);
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("lCF", schema0, "lCF", objectNode0, false, schema_Field_Order0);
      schema_Field0.order();
      assertEquals((-1), schema_Field0.pos());
  }
}
