/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 08 21:52:34 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.Clock;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.List;
import java.util.Stack;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$LocalTimestampMillisConversion_ESTest extends TimeConversions$LocalTimestampMillisConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.LocalTimestampMillisConversion timeConversions_LocalTimestampMillisConversion0 = new TimeConversions.LocalTimestampMillisConversion();
      Long long0 = new Long(0L);
      Stack<String> stack0 = new Stack<String>();
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) stack0, (String) null);
      LocalDateTime localDateTime0 = timeConversions_LocalTimestampMillisConversion0.fromLong(long0, schema0, (LogicalType) null);
      assertNotNull(localDateTime0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.LocalTimestampMillisConversion timeConversions_LocalTimestampMillisConversion0 = new TimeConversions.LocalTimestampMillisConversion();
      ZoneId zoneId0 = ZoneId.systemDefault();
      Clock clock0 = Clock.tickMillis(zoneId0);
      LocalDateTime localDateTime0 = MockLocalDateTime.now(clock0);
      LogicalType logicalType0 = new LogicalType("");
      Long long0 = timeConversions_LocalTimestampMillisConversion0.toLong(localDateTime0, (Schema) null, logicalType0);
      //  // Unstable assertion: assertEquals(1780955551596L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.LocalTimestampMillisConversion timeConversions_LocalTimestampMillisConversion0 = new TimeConversions.LocalTimestampMillisConversion();
      Schema schema0 = timeConversions_LocalTimestampMillisConversion0.getRecommendedSchema();
      assertNull(schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.LocalTimestampMillisConversion timeConversions_LocalTimestampMillisConversion0 = new TimeConversions.LocalTimestampMillisConversion();
      Class<LocalDateTime> class0 = timeConversions_LocalTimestampMillisConversion0.getConvertedType();
      assertFalse(class0.isPrimitive());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.LocalTimestampMillisConversion timeConversions_LocalTimestampMillisConversion0 = new TimeConversions.LocalTimestampMillisConversion();
      String string0 = timeConversions_LocalTimestampMillisConversion0.getLogicalTypeName();
      assertEquals("local-timestamp-millis", string0);
  }
}
