/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 08 21:52:21 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.Instant;
import org.apache.avro.LogicalType;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$TimestampMicrosConversion_ESTest extends TimeConversions$TimestampMicrosConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      System.setCurrentTimeMillis(1000000000L);
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Instant instant0 = MockInstant.now();
      Instant instant1 = MockInstant.minusSeconds(instant0, 1392409281L);
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      LogicalType logicalType0 = new LogicalType("");
      Long long0 = timeConversions_TimestampMicrosConversion0.toLong(instant1, schema0, logicalType0);
      assertEquals((-1391409281000000L), (long)long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Long long0 = new Long(0L);
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Instant instant0 = timeConversions_TimestampMicrosConversion0.fromLong(long0, schema0, (LogicalType) null);
      Long long1 = timeConversions_TimestampMicrosConversion0.toLong(instant0, schema0, (LogicalType) null);
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Long long0 = new Long(3421L);
      Schema schema0 = Protocol.SYSTEM_ERROR;
      LogicalType logicalType0 = new LogicalType("org.apache.avro.data.TimeConversions$TimestampMicrosConversion");
      Instant instant0 = timeConversions_TimestampMicrosConversion0.fromLong(long0, schema0, logicalType0);
      Instant instant1 = MockInstant.minusMillis(instant0, 3421L);
      Long long1 = timeConversions_TimestampMicrosConversion0.toLong(instant1, (Schema) null, (LogicalType) null);
      assertEquals((-3417579L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      String string0 = timeConversions_TimestampMicrosConversion0.adjustAndSetValue("logicalType", "BIG_INTEGER");
      assertEquals("logicalType = BIG_INTEGER.truncatedTo(java.time.temporal.ChronoUnit.MICROS);", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Class<Instant> class0 = timeConversions_TimestampMicrosConversion0.getConvertedType();
      assertFalse(class0.isSynthetic());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Schema schema0 = timeConversions_TimestampMicrosConversion0.getRecommendedSchema();
      assertEquals(Schema.Type.LONG, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      String string0 = timeConversions_TimestampMicrosConversion0.getLogicalTypeName();
      assertEquals("timestamp-micros", string0);
  }
}
