/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 08 21:52:14 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.Instant;
import java.util.List;
import java.util.Vector;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$TimestampMillisConversion_ESTest extends TimeConversions$TimestampMillisConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.TimestampMillisConversion timeConversions_TimestampMillisConversion0 = new TimeConversions.TimestampMillisConversion();
      Vector<Schema> vector0 = new Vector<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) vector0);
      // Undeclared exception!
      try { 
        timeConversions_TimestampMillisConversion0.fromLong((Long) null, schema0, (LogicalType) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.data.TimeConversions$TimestampMillisConversion", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.TimestampMillisConversion timeConversions_TimestampMillisConversion0 = new TimeConversions.TimestampMillisConversion();
      Instant instant0 = MockInstant.ofEpochMilli(2054L);
      Schema schema0 = timeConversions_TimestampMillisConversion0.getRecommendedSchema();
      LogicalType logicalType0 = schema0.getLogicalType();
      Long long0 = timeConversions_TimestampMillisConversion0.toLong(instant0, schema0, logicalType0);
      assertEquals(2054L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.TimestampMillisConversion timeConversions_TimestampMillisConversion0 = new TimeConversions.TimestampMillisConversion();
      String string0 = timeConversions_TimestampMillisConversion0.getLogicalTypeName();
      assertEquals("timestamp-millis", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.TimestampMillisConversion timeConversions_TimestampMillisConversion0 = new TimeConversions.TimestampMillisConversion();
      String string0 = timeConversions_TimestampMillisConversion0.adjustAndSetValue("logicalType", "logicalType");
      assertEquals("logicalType = logicalType.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.TimestampMillisConversion timeConversions_TimestampMillisConversion0 = new TimeConversions.TimestampMillisConversion();
      Class<Instant> class0 = timeConversions_TimestampMillisConversion0.getConvertedType();
      assertFalse(class0.isInterface());
  }
}
