/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 08 21:51:55 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.LocalDate;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$DateConversion_ESTest extends TimeConversions$DateConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.DateConversion timeConversions_DateConversion0 = new TimeConversions.DateConversion();
      Class<LocalDate> class0 = timeConversions_DateConversion0.getConvertedType();
      assertFalse(class0.isSynthetic());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.DateConversion timeConversions_DateConversion0 = new TimeConversions.DateConversion();
      LocalDate localDate0 = MockLocalDate.now();
      Schema.Type schema_Type0 = Schema.Type.INT;
      Schema schema0 = Schema.create(schema_Type0);
      Integer integer0 = timeConversions_DateConversion0.toInt(localDate0, schema0, (LogicalType) null);
      assertEquals(16115, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.DateConversion timeConversions_DateConversion0 = new TimeConversions.DateConversion();
      Schema schema0 = timeConversions_DateConversion0.getRecommendedSchema();
      assertEquals(Schema.Type.INT, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.DateConversion timeConversions_DateConversion0 = new TimeConversions.DateConversion();
      Integer integer0 = new Integer(1);
      Schema.Type schema_Type0 = Schema.Type.FLOAT;
      Schema schema0 = Schema.create(schema_Type0);
      LocalDate localDate0 = timeConversions_DateConversion0.fromInt(integer0, schema0, (LogicalType) null);
      assertNotNull(localDate0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.DateConversion timeConversions_DateConversion0 = new TimeConversions.DateConversion();
      String string0 = timeConversions_DateConversion0.getLogicalTypeName();
      assertEquals("date", string0);
  }
}
