/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 08 21:52:08 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import org.apache.avro.LogicalType;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalTime;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$TimeMicrosConversion_ESTest extends TimeConversions$TimeMicrosConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.TimeMicrosConversion timeConversions_TimeMicrosConversion0 = new TimeConversions.TimeMicrosConversion();
      Long long0 = new Long(226L);
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      LocalTime localTime0 = timeConversions_TimeMicrosConversion0.fromLong(long0, schema0, (LogicalType) null);
      assertNotNull(localTime0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.TimeMicrosConversion timeConversions_TimeMicrosConversion0 = new TimeConversions.TimeMicrosConversion();
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      LocalTime localTime0 = MockLocalTime.now((ZoneId) zoneOffset0);
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Long long0 = timeConversions_TimeMicrosConversion0.toLong(localTime0, schema0, (LogicalType) null);
      assertEquals(51681320000L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.TimeMicrosConversion timeConversions_TimeMicrosConversion0 = new TimeConversions.TimeMicrosConversion();
      String string0 = timeConversions_TimeMicrosConversion0.getLogicalTypeName();
      assertEquals("time-micros", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.TimeMicrosConversion timeConversions_TimeMicrosConversion0 = new TimeConversions.TimeMicrosConversion();
      Schema schema0 = timeConversions_TimeMicrosConversion0.getRecommendedSchema();
      assertEquals(Schema.Type.LONG, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.TimeMicrosConversion timeConversions_TimeMicrosConversion0 = new TimeConversions.TimeMicrosConversion();
      String string0 = timeConversions_TimeMicrosConversion0.adjustAndSetValue("?", "");
      assertEquals("? = .truncatedTo(java.time.temporal.ChronoUnit.MICROS);", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TimeConversions.TimeMicrosConversion timeConversions_TimeMicrosConversion0 = new TimeConversions.TimeMicrosConversion();
      Class<LocalTime> class0 = timeConversions_TimeMicrosConversion0.getConvertedType();
      assertFalse(class0.isArray());
  }
}
