/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 20 14:09:56 GMT 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.FloatNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.NullNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.node.POJONode;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Schema$Field_ESTest extends Schema$Field_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(true);
      HashMap<String, JsonNode> hashMap0 = new HashMap<String, JsonNode>();
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0, hashMap0);
      Schema[] schemaArray0 = new Schema[0];
      Schema schema0 = Schema.createUnion(schemaArray0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field1 = new Schema.Field("DESCENDING", schema0, "hbB\"", objectNode0, false, schema_Field_Order0);
      boolean boolean0 = schema_Field1.equals(schema_Field0);
      assertFalse(boolean0);
      assertEquals("hbB\"", schema_Field1.doc());
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Schema[] schemaArray0 = new Schema[0];
      Schema schema0 = Schema.createUnion(schemaArray0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0, "DESCENDING");
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertTrue(schema_Field1.equals((Object)schema_Field0));
      
      schema_Field0.addProp("DESCENDING", (Object) "DESCENDING");
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FloatNode floatNode0 = FloatNode.valueOf(1597.9246F);
      List<String> list0 = floatNode0.findValuesAsText("DESCENDING");
      Schema schema0 = Schema.createEnum("DESCENDING", "DESCENDING", "DESCENDING", list0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0);
      POJONode pOJONode0 = new POJONode(schema_Field0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field1 = new Schema.Field("DESCENDING", schema0, "DESCENDING", pOJONode0, false, schema_Field_Order0);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertEquals((-1), schema_Field1.pos());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0, "$VALUES");
      Schema schema1 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema1);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertEquals((-1), schema_Field1.pos());
      assertEquals("$VALUES", schema_Field1.doc());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Schema[] schemaArray0 = new Schema[0];
      Schema schema0 = Schema.createUnion(schemaArray0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0, "DESCENDING");
      Schema.Field schema_Field1 = new Schema.Field("InwD", schema0);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertFalse(boolean0);
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(true);
      HashMap<String, JsonNode> hashMap0 = new HashMap<String, JsonNode>();
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0, hashMap0);
      Schema[] schemaArray0 = new Schema[0];
      Schema schema0 = Schema.createUnion(schemaArray0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0);
      NullNode nullNode0 = objectNode0.nullNode();
      boolean boolean0 = schema_Field0.equals(nullNode0);
      assertFalse(boolean0);
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FloatNode floatNode0 = FloatNode.valueOf(1597.9246F);
      List<String> list0 = floatNode0.findValuesAsText("DESCENDING");
      Schema schema0 = Schema.createEnum("DESCENDING", "DESCENDING", "DESCENDING", list0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0);
      boolean boolean0 = schema_Field0.equals(schema_Field0);
      assertTrue(boolean0);
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FloatNode floatNode0 = FloatNode.valueOf(1597.9246F);
      List<String> list0 = floatNode0.findValuesAsText("DESCENDING");
      Schema schema0 = Schema.createEnum("DESCENDING", "DESCENDING", "DESCENDING", list0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
      Schema.Field schema_Field1 = new Schema.Field("DESCENDING", schema0, "DESCENDING", (JsonNode) null, false, schema_Field_Order0);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertEquals((-1), schema_Field1.pos());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("USE_FAST_DOUBLE_PARSER", schema0, "USE_FAST_DOUBLE_PARSER");
      schema_Field0.aliases();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Schema[] schemaArray0 = new Schema[0];
      Schema schema0 = Schema.createUnion(schemaArray0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0, "DESCENDING");
      schema_Field0.addAlias("DESCENDING");
      Set<String> set0 = schema_Field0.aliases();
      assertTrue(set0.contains("DESCENDING"));
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Schema[] schemaArray0 = new Schema[0];
      Schema schema0 = Schema.createUnion(schemaArray0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0, "com.fasterxml.jackson.databind.cfg.ConfigOverride$Empty");
      schema_Field0.addAlias("com.fasterxml.jackson.databind.cfg.ConfigOverride$Empty");
      schema_Field0.addAlias("DESCENDING");
      assertEquals("com.fasterxml.jackson.databind.cfg.ConfigOverride$Empty", schema_Field0.doc());
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      HashMap<String, JsonNode> hashMap0 = new HashMap<String, JsonNode>();
      ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0, hashMap0);
      Schema[] schemaArray0 = new Schema[0];
      Schema schema0 = Schema.createUnion(schemaArray0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0, "DESCENDING", objectNode0, false, schema_Field_Order0);
      boolean boolean0 = schema_Field0.hasDefaultValue();
      assertTrue(boolean0);
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FloatNode floatNode0 = FloatNode.valueOf(1597.9246F);
      List<String> list0 = floatNode0.findValuesAsText("DESCENDING");
      Schema schema0 = Schema.createEnum("DESCENDING", "DESCENDING", "DESCENDING", list0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0);
      boolean boolean0 = schema_Field0.hasDefaultValue();
      assertFalse(boolean0);
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field((String) null, (Schema) null, (String) null, object0, schema_Field_Order0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Null name
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field((String) null, (Schema) null, (String) null, (Object) null, schema_Field_Order0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Null name
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Schema[] schemaArray0 = new Schema[0];
      Schema schema0 = Schema.createUnion(schemaArray0);
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("#-G`\"wLcc6L[ATJ\"U#", schema0, "#-G`\"wLcc6L[ATJ\"U#", object0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Illegal initial character: #-G`\"wLcc6L[ATJ\"U#
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedList<Schema> linkedList0 = new LinkedList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) linkedList0);
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("FAIL_ON_EMPTY_BEANS", schema0, "FAIL_ON_EMPTY_BEANS", linkedList0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Invalid default for field FAIL_ON_EMPTY_BEANS: [] not a []
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Schema[] schemaArray0 = new Schema[0];
      Schema schema0 = Schema.createUnion(schemaArray0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0, "com.fasterxml.jackson.databind.cfg.ConfigOverride$Empty");
      schema_Field0.addAlias("DESCENDING");
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertEquals("com.fasterxml.jackson.databind.cfg.ConfigOverride$Empty", schema_Field1.doc());
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Schema[] schemaArray0 = new Schema[0];
      Schema schema0 = Schema.createUnion(schemaArray0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0, "DESCENDING");
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertTrue(boolean0);
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      FloatNode floatNode0 = FloatNode.valueOf(1597.9246F);
      List<String> list0 = floatNode0.findValuesAsText("DESCENDING");
      Schema schema0 = Schema.createEnum("DESCENDING", "DESCENDING", "hbB\"", list0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0, "hbB\"");
      int int0 = schema_Field0.pos();
      assertEquals((-1), int0);
      assertEquals("hbB\"", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("USE_FAST_DOUBLE_PARSER", schema0, "USE_FAST_DOUBLE_PARSER");
      schema_Field0.defaultVal();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("USE_FAST_DOUBLE_PARSER", schema0, "USE_FAST_DOUBLE_PARSER");
      schema_Field0.hashCode();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      FloatNode floatNode0 = FloatNode.valueOf(1597.9246F);
      List<String> list0 = floatNode0.findValuesAsText("DESCENDING");
      Schema schema0 = Schema.createEnum("DESCENDING", "DESCENDING", "DESCENDING", list0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0);
      String string0 = schema_Field0.doc();
      assertNull(string0);
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Schema[] schemaArray0 = new Schema[0];
      Schema schema0 = Schema.createUnion(schemaArray0);
      Schema.Field schema_Field0 = new Schema.Field("si", schema0);
      String string0 = schema_Field0.toString();
      assertEquals("si type:UNION pos:-1", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      FloatNode floatNode0 = FloatNode.valueOf(1597.9246F);
      List<String> list0 = floatNode0.findValuesAsText("DESCENDING");
      Schema schema0 = Schema.createEnum("DESCENDING", "o^>bA", "hbB\"", list0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0);
      schema_Field0.name();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      FloatNode floatNode0 = FloatNode.valueOf(1597.9246F);
      List<String> list0 = floatNode0.findValuesAsText("DESCENDING");
      Schema schema0 = Schema.createEnum("DESCENDING", "DESCENDING", "DESCENDING", list0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0);
      schema_Field0.defaultValue();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      FloatNode floatNode0 = FloatNode.valueOf((short)0);
      List<String> list0 = floatNode0.findValuesAsText("DESCENDING");
      Schema schema0 = Schema.createEnum("DESCENDING", "DESCENDING", "DESCENDING", list0);
      Schema.Field schema_Field0 = new Schema.Field("DESCENDING", schema0);
      schema_Field0.schema();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Schema schema0 = Schema.createEnum("DESCdNDING", "DESCdNDING", "DESCdNDING", (List<String>) arrayList0);
      Schema.Field schema_Field0 = new Schema.Field("DESCdNDING", schema0, "DESCdNDING");
      schema_Field0.order();
      assertEquals((-1), schema_Field0.pos());
  }
}
