/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 20 14:11:08 GMT 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import org.apache.avro.NameValidator;
import org.apache.avro.ParseContext;
import org.apache.avro.Schema;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Schema$Parser_ESTest extends Schema$Parser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      String[] stringArray0 = new String[5];
      stringArray0[0] = "\"as@~3FY~*xaSeYi";
      // Undeclared exception!
      try { 
        schema_Parser0.parse("\"as@~3FY~*xaSeYi", stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Unknown schema: org.apache.avro.compiler.UnresolvedSchema_17
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      ArrayList<Schema> arrayList0 = new ArrayList<Schema>(0);
      Schema schema0 = Schema.createUnion((List<Schema>) arrayList0);
      List<Schema> list0 = List.of(schema0);
      // Undeclared exception!
      try { 
        schema_Parser0.addTypes((Iterable<Schema>) list0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // You can only put a named schema into the context
         //
         verifyException("org.apache.avro.ParseContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      boolean boolean0 = schema_Parser0.getValidateDefaults();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      // Undeclared exception!
      try { 
        schema_Parser0.parse((File) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      assertTrue(schema_Parser0.getValidateDefaults());
      
      schema_Parser0.setValidateDefaults(false);
      assertFalse(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      schema_Parser0.getTypes();
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      // Undeclared exception!
      try { 
        schema_Parser0.parse((InputStream) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Cannot parse <null> schema
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }
}
