/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 08 21:52:40 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.LocalDateTime;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$LocalTimestampMicrosConversion_ESTest extends TimeConversions$LocalTimestampMicrosConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.LocalTimestampMicrosConversion timeConversions_LocalTimestampMicrosConversion0 = new TimeConversions.LocalTimestampMicrosConversion();
      String string0 = timeConversions_LocalTimestampMicrosConversion0.getLogicalTypeName();
      assertEquals("local-timestamp-micros", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.LocalTimestampMicrosConversion timeConversions_LocalTimestampMicrosConversion0 = new TimeConversions.LocalTimestampMicrosConversion();
      Class<LocalDateTime> class0 = timeConversions_LocalTimestampMicrosConversion0.getConvertedType();
      assertEquals(17, class0.getModifiers());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.LocalTimestampMicrosConversion timeConversions_LocalTimestampMicrosConversion0 = new TimeConversions.LocalTimestampMicrosConversion();
      Long long0 = new Long((-1L));
      Schema schema0 = timeConversions_LocalTimestampMicrosConversion0.getRecommendedSchema();
      LogicalType logicalType0 = new LogicalType(".(Q'^xn9AL [B^>F4");
      LocalDateTime localDateTime0 = timeConversions_LocalTimestampMicrosConversion0.fromLong(long0, schema0, logicalType0);
      Long long1 = timeConversions_LocalTimestampMicrosConversion0.toLong(localDateTime0, schema0, logicalType0);
      assertEquals((-1L), (long)long1);
  }
}
