/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 08 21:52:51 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.LocalDateTime;
import org.apache.avro.LogicalType;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$LocalTimestampNanosConversion_ESTest extends TimeConversions$LocalTimestampNanosConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.LocalTimestampNanosConversion timeConversions_LocalTimestampNanosConversion0 = new TimeConversions.LocalTimestampNanosConversion();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      LogicalType logicalType0 = new LogicalType("local-timestamp-nanos");
      Long long0 = timeConversions_LocalTimestampNanosConversion0.toLong(localDateTime0, schema0, logicalType0);
      assertEquals(1392409281320000000L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.LocalTimestampNanosConversion timeConversions_LocalTimestampNanosConversion0 = new TimeConversions.LocalTimestampNanosConversion();
      Class<LocalDateTime> class0 = timeConversions_LocalTimestampNanosConversion0.getConvertedType();
      assertFalse(class0.isArray());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.LocalTimestampNanosConversion timeConversions_LocalTimestampNanosConversion0 = new TimeConversions.LocalTimestampNanosConversion();
      String string0 = timeConversions_LocalTimestampNanosConversion0.getLogicalTypeName();
      assertEquals("local-timestamp-nanos", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.LocalTimestampNanosConversion timeConversions_LocalTimestampNanosConversion0 = new TimeConversions.LocalTimestampNanosConversion();
      Schema schema0 = timeConversions_LocalTimestampNanosConversion0.getRecommendedSchema();
      Long long0 = new Long(0L);
      LogicalType logicalType0 = schema0.getLogicalType();
      LocalDateTime localDateTime0 = timeConversions_LocalTimestampNanosConversion0.fromLong(long0, schema0, logicalType0);
      assertNotNull(localDateTime0);
  }
}
