/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 08 21:52:27 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.Instant;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$TimestampNanosConversion_ESTest extends TimeConversions$TimestampNanosConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      MockDate mockDate0 = new MockDate(0, 0, 0, 0, 0, (-377));
      Instant instant0 = mockDate0.toInstant();
      LogicalType logicalType0 = new LogicalType("]}/5zOelg:]");
      Long long0 = timeConversions_TimestampNanosConversion0.toLong(instant0, (Schema) null, logicalType0);
      assertEquals((-2209075577000000000L), (long)long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      MockDate mockDate0 = new MockDate();
      Instant instant0 = mockDate0.toInstant();
      Schema schema0 = timeConversions_TimestampNanosConversion0.getRecommendedSchema();
      LogicalType logicalType0 = schema0.getLogicalType();
      Long long0 = timeConversions_TimestampNanosConversion0.toLong(instant0, schema0, logicalType0);
      assertEquals(1392409281320000000L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Class<Instant> class0 = timeConversions_TimestampNanosConversion0.getConvertedType();
      assertEquals(17, class0.getModifiers());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      String string0 = timeConversions_TimestampNanosConversion0.getLogicalTypeName();
      assertEquals("timestamp-nanos", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      String string0 = timeConversions_TimestampNanosConversion0.adjustAndSetValue("]}/5zOelg:]", "com.fasterxml.jackson.databind.MapperFeature");
      assertEquals("]}/5zOelg:] = com.fasterxml.jackson.databind.MapperFeature.truncatedTo(java.time.temporal.ChronoUnit.NANOS);", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Long long0 = new Long((-158L));
      LogicalType logicalType0 = new LogicalType("|]S! FOm");
      Instant instant0 = timeConversions_TimestampNanosConversion0.fromLong(long0, (Schema) null, logicalType0);
      Long long1 = timeConversions_TimestampNanosConversion0.toLong(instant0, (Schema) null, logicalType0);
      assertEquals(998999842L, (long)long1);
  }
}
