/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 11 16:24:55 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.LocalDate;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$DateConversion_ESTest extends TimeConversions$DateConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.DateConversion timeConversions_DateConversion0 = new TimeConversions.DateConversion();
      Class<LocalDate> class0 = timeConversions_DateConversion0.getConvertedType();
      assertEquals("class java.time.LocalDate", class0.toString());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.DateConversion timeConversions_DateConversion0 = new TimeConversions.DateConversion();
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1193L));
      Schema.Type schema_Type0 = Schema.Type.STRING;
      Schema schema0 = Schema.create(schema_Type0);
      Integer integer0 = timeConversions_DateConversion0.toInt(localDate0, schema0, (LogicalType) null);
      assertEquals((-1193), (int)integer0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.DateConversion timeConversions_DateConversion0 = new TimeConversions.DateConversion();
      Schema schema0 = timeConversions_DateConversion0.getRecommendedSchema();
      assertNull(schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.DateConversion timeConversions_DateConversion0 = new TimeConversions.DateConversion();
      Integer integer0 = new Integer(201);
      LogicalType logicalType0 = new LogicalType("e");
      LocalDate localDate0 = timeConversions_DateConversion0.fromInt(integer0, (Schema) null, logicalType0);
      assertNotNull(localDate0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.DateConversion timeConversions_DateConversion0 = new TimeConversions.DateConversion();
      String string0 = timeConversions_DateConversion0.getLogicalTypeName();
      assertEquals("date", string0);
  }
}
