/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 11 16:25:13 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.Instant;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$TimestampMillisConversion_ESTest extends TimeConversions$TimestampMillisConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.TimestampMillisConversion timeConversions_TimestampMillisConversion0 = new TimeConversions.TimestampMillisConversion();
      Schema schema0 = timeConversions_TimestampMillisConversion0.getRecommendedSchema();
      Long long0 = new Long(0L);
      LogicalType logicalType0 = schema0.getLogicalType();
      Instant instant0 = timeConversions_TimestampMillisConversion0.fromLong(long0, schema0, logicalType0);
      assertNotNull(instant0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.TimestampMillisConversion timeConversions_TimestampMillisConversion0 = new TimeConversions.TimestampMillisConversion();
      Instant instant0 = MockInstant.now();
      Long long0 = timeConversions_TimestampMillisConversion0.toLong(instant0, (Schema) null, (LogicalType) null);
      assertEquals(1392409281320L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.TimestampMillisConversion timeConversions_TimestampMillisConversion0 = new TimeConversions.TimestampMillisConversion();
      String string0 = timeConversions_TimestampMillisConversion0.getLogicalTypeName();
      assertEquals("timestamp-millis", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.TimestampMillisConversion timeConversions_TimestampMillisConversion0 = new TimeConversions.TimestampMillisConversion();
      String string0 = timeConversions_TimestampMillisConversion0.adjustAndSetValue("timestamp-millis", "timestamp-millis");
      assertEquals("timestamp-millis = timestamp-millis.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.TimestampMillisConversion timeConversions_TimestampMillisConversion0 = new TimeConversions.TimestampMillisConversion();
      Class<Instant> class0 = timeConversions_TimestampMillisConversion0.getConvertedType();
      assertFalse(class0.isSynthetic());
  }
}
