/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 11 16:25:33 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$LocalTimestampMillisConversion_ESTest extends TimeConversions$LocalTimestampMillisConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.LocalTimestampMillisConversion timeConversions_LocalTimestampMillisConversion0 = new TimeConversions.LocalTimestampMillisConversion();
      ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutesSeconds(0, 0, 0);
      LocalDateTime localDateTime0 = MockLocalDateTime.now((ZoneId) zoneOffset0);
      LogicalType logicalType0 = new LogicalType("java.util.");
      Long long0 = timeConversions_LocalTimestampMillisConversion0.toLong(localDateTime0, (Schema) null, logicalType0);
      assertEquals(1392409281320L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.LocalTimestampMillisConversion timeConversions_LocalTimestampMillisConversion0 = new TimeConversions.LocalTimestampMillisConversion();
      Schema schema0 = timeConversions_LocalTimestampMillisConversion0.getRecommendedSchema();
      LogicalType logicalType0 = new LogicalType("local-timestamp-millis");
      // Undeclared exception!
      try { 
        timeConversions_LocalTimestampMillisConversion0.fromLong((Long) null, schema0, logicalType0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.data.TimeConversions$TimestampMillisConversion", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.LocalTimestampMillisConversion timeConversions_LocalTimestampMillisConversion0 = new TimeConversions.LocalTimestampMillisConversion();
      Class<LocalDateTime> class0 = timeConversions_LocalTimestampMillisConversion0.getConvertedType();
      assertEquals("class java.time.LocalDateTime", class0.toString());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.LocalTimestampMillisConversion timeConversions_LocalTimestampMillisConversion0 = new TimeConversions.LocalTimestampMillisConversion();
      String string0 = timeConversions_LocalTimestampMillisConversion0.getLogicalTypeName();
      assertEquals("local-timestamp-millis", string0);
  }
}
