/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 11 16:25:20 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.time.temporal.TemporalUnit;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$TimestampMicrosConversion_ESTest extends TimeConversions$TimestampMicrosConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Schema schema0 = timeConversions_TimestampMicrosConversion0.getRecommendedSchema();
      LogicalType logicalType0 = new LogicalType("k");
      Long long0 = new Long((-1897L));
      Instant instant0 = timeConversions_TimestampMicrosConversion0.fromLong(long0, schema0, logicalType0);
      Long long1 = timeConversions_TimestampMicrosConversion0.toLong(instant0, schema0, logicalType0);
      assertEquals((-1897L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Schema schema0 = timeConversions_TimestampMicrosConversion0.getRecommendedSchema();
      Long long0 = new Long(0L);
      LogicalType logicalType0 = new LogicalType("k");
      Instant instant0 = timeConversions_TimestampMicrosConversion0.fromLong(long0, schema0, logicalType0);
      ChronoUnit chronoUnit0 = ChronoUnit.SECONDS;
      Instant instant1 = MockInstant.minus(instant0, 1395L, (TemporalUnit) chronoUnit0);
      Long long1 = timeConversions_TimestampMicrosConversion0.toLong(instant1, schema0, logicalType0);
      assertEquals((-1395000000L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      String string0 = timeConversions_TimestampMicrosConversion0.adjustAndSetValue((String) null, "");
      assertEquals("null = .truncatedTo(java.time.temporal.ChronoUnit.MICROS);", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Class<Instant> class0 = timeConversions_TimestampMicrosConversion0.getConvertedType();
      assertFalse(class0.isAnnotation());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      Schema schema0 = timeConversions_TimestampMicrosConversion0.getRecommendedSchema();
      Long long0 = new Long(0L);
      LogicalType logicalType0 = new LogicalType("k");
      Instant instant0 = timeConversions_TimestampMicrosConversion0.fromLong(long0, schema0, logicalType0);
      Long long1 = timeConversions_TimestampMicrosConversion0.toLong(instant0, schema0, logicalType0);
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TimeConversions.TimestampMicrosConversion timeConversions_TimestampMicrosConversion0 = new TimeConversions.TimestampMicrosConversion();
      String string0 = timeConversions_TimestampMicrosConversion0.getLogicalTypeName();
      assertEquals("timestamp-micros", string0);
  }
}
