/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 11 16:25:27 GMT 2026
 */

package org.apache.avro.data;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.Instant;
import org.apache.avro.LogicalType;
import org.apache.avro.Schema;
import org.apache.avro.data.TimeConversions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeConversions$TimestampNanosConversion_ESTest extends TimeConversions$TimestampNanosConversion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Long long0 = new Long(0L);
      Schema schema0 = Schema.createFixed("ALLOWED", "ZxQ~5", "ZxQ~5", 1);
      LogicalType logicalType0 = new LogicalType("a|7OrDNO8JD<<@");
      Instant instant0 = timeConversions_TimestampNanosConversion0.fromLong(long0, schema0, logicalType0);
      Instant instant1 = MockInstant.minusNanos(instant0, 989L);
      Long long1 = timeConversions_TimestampNanosConversion0.toLong(instant1, schema0, logicalType0);
      assertEquals(998999011L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Schema schema0 = Schema.createFixed("ALLOWED", "ZxQ~5", "ZxQ~5", 1);
      LogicalType logicalType0 = new LogicalType("a|7OrDNO8JD<<@");
      Instant instant0 = MockInstant.ofEpochSecond((-2995L));
      Long long0 = timeConversions_TimestampNanosConversion0.toLong(instant0, schema0, logicalType0);
      assertEquals((-2995000000000L), (long)long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Class<Instant> class0 = timeConversions_TimestampNanosConversion0.getConvertedType();
      assertFalse(class0.isSynthetic());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      String string0 = timeConversions_TimestampNanosConversion0.getLogicalTypeName();
      assertEquals("timestamp-nanos", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      String string0 = timeConversions_TimestampNanosConversion0.adjustAndSetValue("", "");
      assertEquals(" = .truncatedTo(java.time.temporal.ChronoUnit.NANOS);", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Long long0 = new Long(0L);
      Schema schema0 = Schema.createFixed("ALLOWED", "ZxQ~5", "ZxQ~5", 1);
      LogicalType logicalType0 = new LogicalType("a|7OrDNO8JD<<@");
      Instant instant0 = timeConversions_TimestampNanosConversion0.fromLong(long0, schema0, logicalType0);
      Long long1 = timeConversions_TimestampNanosConversion0.toLong(instant0, schema0, logicalType0);
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TimeConversions.TimestampNanosConversion timeConversions_TimestampNanosConversion0 = new TimeConversions.TimestampNanosConversion();
      Schema schema0 = timeConversions_TimestampNanosConversion0.getRecommendedSchema();
      assertNull(schema0.getDoc());
  }
}
