/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 25 15:06:06 GMT 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.PipedInputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.avro.NameValidator;
import org.apache.avro.ParseContext;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Schema$Parser_ESTest extends Schema$Parser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
      String[] stringArray0 = new String[4];
      stringArray0[0] = "\"+>b tt2Zd5}G*<Wwe%";
      // Undeclared exception!
      try { 
        schema_Parser0.parse("\"+>b tt2Zd5}G*<Wwe%", stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Unknown schema: org.apache.avro.compiler.UnresolvedSchema_17
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      List<Schema> list0 = List.of(schema0, schema0);
      // Undeclared exception!
      try { 
        schema_Parser0.addTypes((Iterable<Schema>) list0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // You can only put a named schema into the context
         //
         verifyException("org.apache.avro.ParseContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
      boolean boolean0 = schema_Parser0.getValidateDefaults();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
      HashMap<String, Schema> hashMap0 = new HashMap<String, Schema>();
      Schema.Parser schema_Parser1 = schema_Parser0.addTypes((Map<String, Schema>) hashMap0);
      assertTrue(schema_Parser1.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
      // Undeclared exception!
      try { 
        schema_Parser0.parseInternal("");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Cannot parse <null> schema
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
      // Undeclared exception!
      try { 
        schema_Parser0.parse((File) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      assertTrue(schema_Parser0.getValidateDefaults());
      
      schema_Parser0.setValidateDefaults(false);
      assertFalse(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      schema_Parser0.getTypes();
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      try { 
        schema_Parser0.parse((InputStream) pipedInputStream0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedInputStream", e);
      }
  }
}
