/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Jul 25 15:06:10 GMT 2026
 */

package org.apache.avro;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Schema$SeenPair_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.avro.Schema$SeenPair"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Schema$SeenPair_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.avro.Schema$MapSchema",
      "org.apache.avro.Schema$Field",
      "org.apache.avro.Schema$Name",
      "org.apache.avro.Schema$EnumSchema",
      "org.apache.avro.Schema$LongSchema",
      "com.fasterxml.jackson.core.Versioned",
      "org.apache.avro.Schema$DoubleSchema",
      "org.apache.avro.Schema$BooleanSchema",
      "org.apache.avro.Schema$SeenPair",
      "org.apache.avro.Schema$UnionSchema",
      "org.apache.avro.Schema$NamedSchema",
      "org.apache.avro.Schema$NullSchema",
      "org.apache.avro.JsonProperties",
      "org.apache.avro.Schema$BytesSchema",
      "org.apache.avro.Schema$LockableArrayList",
      "org.apache.avro.NameValidator",
      "org.apache.avro.Schema",
      "org.apache.avro.Schema$IntSchema",
      "org.apache.avro.Schema$Parser",
      "com.fasterxml.jackson.core.JsonParser",
      "org.apache.avro.Schema$SerializableSchema",
      "org.apache.avro.Schema$Names",
      "org.apache.avro.Schema$RecordSchema",
      "org.apache.avro.Schema$FloatSchema",
      "org.apache.avro.Schema$Type",
      "org.apache.avro.Schema$StringSchema",
      "org.apache.avro.Schema$FixedSchema",
      "org.apache.avro.Schema$ArraySchema"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Schema$SeenPair_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.avro.Schema$SeenPair"
    );
  }
}
